### PR TITLE
The contributors heading coming out of the div iphone 4 check #303

### PR DESCRIPTION
**Pull request by aayusharora**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://aayusharora.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@aayusharora Wrt Issue #303 , Could you post a before- after screenshot ?

**Comment by aayusharora** [comment]
Issue #303
Before:

After:

**Comment by jigyasa-grover** [comment]
Okay, Thanks.

**Pull request merged**
