### PR TITLE
added my photo details

### PR DESCRIPTION
**Pull request by ghost**
photo:sanjay.jpg, details at students.yml

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://sanjaytharagesh31.github.io/gci15.fossasia.org

**Comment by ghost** [comment]
have i done everything?

**Comment by ghost** [comment]
yes ,thats right.

when will it be merged

**Comment by roonyh** [comment]
Good, but you are adding an unnecessary file in this commit. `_data/students~`  

Please remove it.

And you can put your work in a single commit so it look nicer. You can do this with squashing git commits. Learn about it and try to put everything in a single commit.

**Comment by ghost** [comment]
now i have removed the students.yml~ file

**Comment by ghost** [comment]
now i have removed the students.yml~ file

**Comment by roonyh** [comment]
Ok, good. Next step is [squashing](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) the four commits into one. Let me know if you have any trouble doing this.

You will have to use `-f` flag when pushing afterwards. `git push -f`

**Comment by ghost** [comment]
can u help me to this

**Comment by roonyh** [comment]
@sanjaytharagesh31 Sure. First you will have to install git to use in command line if you are not doing that now. Then try reading http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html.

If you ran into a specific issue tell us the trouble. 

Do you have git installed for command line in your machine?

Then try git rebase -i HEAD~4 and follow the instructions.

**Comment by ghost** [comment]
I did as said by you.
The problem which i am facing now is how to save and exit from the git editor
(where i changed pick into squash)

**Comment by ghost** [comment]
Yes i have git installed in my computer

**Comment by roonyh** [comment]
Ok! So it depend on what editor you have. It could be vim. In that case: http://stackoverflow.com/questions/11828270/how-to-exit-the-vim-editor

It also could be nano: http://mintaka.sdsu.edu/reu/nano.html

Send me a screen shot if not sure.

**Comment by ghost** [comment]
giteditor1 : after pressing ^o

**Comment by ghost** [comment]
what to do?

**Comment by ghost** [comment]
Have i done with quashing?

**Comment by roonyh** [comment]
Not perfectly fine. see https://github.com/fossasia/gci15.fossasia.org/pull/428/commits

There are two commits.

And see files you changed: https://github.com/fossasia/gci15.fossasia.org/pull/428/files
I don't think you need to change the css file.

**Comment by ghost** [comment]
i dont get what to do

**Comment by ghost** [comment]
better shall i delete everything (github account) and do every thing from
first

**Comment by roonyh** [comment]
Ok, that will be easier for you.

**Pull request closed without merging**
