### PR TITLE
#91 Bad width to media section on mobile phones

### PR DESCRIPTION
**Pull request by aayusharora**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://aayusharora.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@aayusharora please fix this.
screenshot_20151228-100820

**Comment by aayusharora** [comment]
@mananwason ,I am not getting an idea ,why it is looking like this ,consider  http://aayusharora.github.io/gci15.fossasia.org (my pull request ),it is correct on nexus 5 also

**Comment by mananwason** [comment]
@aayusharora I am still getting this error on my phone. I am using Chrome on Nexus 5.
screenshot_20151231-231337

**Comment by aayusharora** [comment]
@mananwason  Can you tell me ,How the gplus section should look like on mobile ,it is giving two results thats why there is problem,
  OR

**Comment by aayusharora** [comment]
@mananwason ,also check this  #277 new pull request ,I think its working fine

**Comment by jigyasa-grover** [comment]
@aayusharora So shall we close this ?
Considering we have 2 PRs (#244 and #277 ) for the same issue #91 by you  ...

**Comment by aayusharora** [comment]
@jig08 ,yes close this ,and consider #277

**Pull request closed without merging**
