### PR TITLE
Re-added Students and Fixed Image and formatting

### PR DESCRIPTION
**Pull request by tansanrao**
Re-added student Hannan Ali and Tanuj Rao.
Fixed Image for student Raheel Saghir.
Added missing hyphens.

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://tansanrao.github.io/gci15.fossasia.org

**Comment by tansanrao** [comment]
working at http://tansanrao.github.io/gci15.fossasia.org/

**Comment by tansanrao** [comment]
@jig08

**Comment by mananwason** [comment]
@tansanrao please squash all relevant commits and remote merge commits. Thanks!

**Comment by mananwason** [comment]
@tansanrao please squash all relevant commits and remote merge commits. Thanks!

**Comment by tansanrao** [comment]
Not near a pc at the moment I'll do it as soon as possible.

**Comment by mananwason** [comment]
:+1:

**Comment by tansanrao** [comment]
Squashed and ready for merging @mananwason

**Pull request merged**
