### PR TITLE
Add FOSSASIA social media section

### PR DESCRIPTION
**Pull request by PolBaladas**

### CODE REVIEW

**Comment by mariobehling** [comment]
Please resolve the merge conflicts. Thank you!

**Comment by harshkothari410** [comment]
Twitter feed is not working. 

Do one thing. Use Git pull first and then submit the changes.

**Comment by PolBaladas** [comment]
Resolved merge conflicts.
Thanks!
(The twitter feed should work)

**Comment by SaptakS** [comment]
Seems good to me.. Thanks for the contribution.

**Comment by PolBaladas** [comment]
Great, Thanks!

**Pull request merged**
