### PR TITLE
add picture and credentials of student abdulhannanali

### PR DESCRIPTION
**Pull request by abdulhannanali**
Hi! I am adding my credentials and picture to the gci :smile:

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://abdulhannanali.github.io/gci15.fossasia.org

**Comment by abdulhannanali** [comment]
Thank you mentor @jig08 You are awesome :+1: 
Now I am going to submit the task. :smile:

**Comment by abdulhannanali** [comment]
Also, really proud to be a member of FOSSASIA TEAM GCI 2015

**Comment by jigyasa-grover** [comment]
@abdulhannanali Thank You :)
We are glad to have you at @fossasia !

**Pull request merged**
