### PR TITLE
Made the newsletter div responsive. closes #622

### LINKED ISSUE #622: Newsletter Prompt issues
- The Newsletter prompt is not visible on devices with less than a width of 325px
  sec4
- The Newsletter prompt is unresponsive on devices with a width greater than 325px
  nrsz

### PR DESCRIPTION
**Pull request by yasoob**
closes #622

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://yasoob.github.io/gci15.fossasia.org

**Comment by Yathannsh** [comment]
@yasoob, it doesn't seem to be responsive 
cx

**Comment by yasoob** [comment]
@Yathannsh It is working fine on my end. I am not sure why it is not displaying correctly on your end. Can someone else please verify the problem as well? 
screenshot from 2016-01-24 00 18 38

**Comment by mananwason** [comment]
@yasoob I am also facing the same issue. Some of the g+ batch is overflowing to the right increasing the width of the web page.

**Comment by yasoob** [comment]
@mananwason That is the G+ issue then and not of the newsletter div. This PR is good to merge if that is the case. I will see what I can do regarding the G+ div in a new PR. :smile:

**Comment by mananwason** [comment]
okay cool then. I'll merge this. We can look at this issue as a separate one. @Yathannsh @yasoob One of you guys can create the new issue for this.

**Comment by yasoob** [comment]
Let me make it.

**Pull request merged**
