### PR TITLE
Added project and name

### PR DESCRIPTION
**Pull request by r4huln**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://r4huln.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@r4huln Squash your commits and then we shall merge it. Refer [this](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) for help.

**Comment by r4huln** [comment]
I  squashed commits

**Comment by r4huln** [comment]
How do I resolve merge conflicts?

**Comment by mananwason** [comment]
@r4huln Just saw the commits. A lot of code from the commits already exists in the repo. I am closing this PR. For the things you wanted to add via this commit, you can create a new PR. Please update your fork first by merging upstream and master, then you can begin working. Thanks!

**Pull request closed without merging**
