### PR TITLE
Updated credentials

### PR DESCRIPTION
**Pull request by BohJieQi**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://BohJieQi.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
Hey Hey @BohJieQi `239 files changed` ? That's a lot.
You just had to add your image in `img/students` and details in `_data/students.yml` following the pattern.
Hope this is clearer, let know in case of any issues :)

**Comment by BohJieQi** [comment]
Yeah sorry, I copied the image and data files, edited them then replaced them with the ones in my local repository. I only added my image and data, sorry for any inconvenience :/

**Comment by jigyasa-grover** [comment]
No issues :)
Send an updated PR.

**Pull request closed without merging**
