### PR TITLE
Added a task screenshot

### PR DESCRIPTION
**Pull request by neerajp99**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://neerajp99.github.io/gci15.fossasia.org

**Comment by pythad** [comment]
@neerajp99, hello, it seems that the url has to be `http://neerajp99.github.io/distancetime/` instead of `http://neerajp99.github.io/distancetime./` as your one isn't valid. Also I think you just copied `Checkers` title and it has to be something like `Distance calculator`. Could you check this?

**Comment by jigyasa-grover** [comment]
@neerajp99 Will you make the desired changes pls ?

**Comment by jigyasa-grover** [comment]
@neerajp99 Are you working on this or shall we close it ?

**Pull request closed without merging**
