### PR TITLE
Added bio and picture

### PR DESCRIPTION
**Pull request by jmurzaku**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://JamMurz.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@JamMurz there are 2 commit messages here. Please change it to one. You can do this by editing commit messages and commenting one of them. Thanks!
screen shot 2016-01-03 at 11 08 00 am

**Comment by jmurzaku** [comment]
@mananwason  i fixed it

**Comment by mananwason** [comment]
Cool. Merged!

**Pull request merged**
