### PR TITLE
Social Icons Bug Fix

### PR DESCRIPTION
**Pull request by sh4dowb**
Google Code In name: Mehmet Cagri Ari

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://hesapadim.github.io/gci15.fossasia.org

**Comment by roonyh** [comment]
Thanks! But it's not clear to me what's the issue you are fixing. Could you please describe or give me a link?

**Comment by sh4dowb** [comment]
http://gci15.fossasia.org/
Hover over a student, there aren't images of social networks

http://hesapadim.github.io/gci15.fossasia.org
Here is :)

**Comment by shashank-sharma** [comment]
If you notice the social icon behaviour in footer is pretty much similar to that which you just fixed. It supposed to be look different. I guess you just replaced that rather than fixing it. It might be possible that I am wrong but from previous version of the site I have never seen this social icon before and there also no history related change in social icon in students, mentors section. But after seeing this image I am pretty sure its not correct. See that its complete black box

screenshot from 2016-01-03 00 20 33

**Comment by sh4dowb** [comment]
gci15.fossasia.org
One box? Yes it's blog's icon. I couldn't find any blog icon in Fossasia's source code. So i left it blank :)

**Comment by shashank-sharma** [comment]
You are not understanding. Let me help you see this image : It must look like this. It is showing black because there is no icon in footer which can show the blog icon.
screenshot from 2016-01-03 00 25 43

**Comment by sh4dowb** [comment]
https://github.com/fossasia/gci15.fossasia.org/pull/289
He is true :)

**Pull request closed without merging**
