### PR TITLE
Fixed id contributors 

### PR DESCRIPTION
**Pull request by shashank-sharma**
Whenever we click to mentors link in header menu then it scroll down to move at mentors section where we see mentors head word written on it. As shows in image and it does same with students link but whenever we click on contributors link then it do scroll down but then contributors head word doesn't show and it get leave behind. As shown in image.
screenshot from 2015-12-28 16 05 09
screenshot from 2015-12-28 16 05 24
screenshot from 2015-12-28 16 05 38
##### So here is the updated image. I removed that contributor id and replaced it.

screenshot from 2015-12-28 16 07 33

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://shashank-sharma.github.io/gci15.fossasia.org

**Comment by shashank-sharma** [comment]
Can we count this merge as this [Task](https://codein.withgoogle.com/tasks/4784931142107136/?sp-organization=4625502878826496&sp-is_beginner=False)

**Comment by roonyh** [comment]
Thanks for noticing and fixing this! Were you awarded a task for this? If not could you also make the images themselves link to contributors' github pages? And remove the small Github icon below them?

**Comment by shashank-sharma** [comment]
@roonyh I have commit it and you can check this Image now its working fine.
screenshot from 2015-12-28 23 40 57

**Comment by jigyasa-grover** [comment]
@roonyh , @shashank-sharma 's fix is working fine at http://shashank-sharma.github.io/gci15.fossasia.org
I am merging this .

**Pull request merged**
