### PR TITLE
Added my blog-post

### PR DESCRIPTION
**Pull request by yasoob**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://yasoob.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@yasoob Resolve conflicts please.

**Comment by yasoob** [comment]
Working on it.

**Comment by yasoob** [comment]
@mananwason done.

**Comment by codethejason** [comment]
@yasoob With the new blog posts section you can show your blog content on the site. #554

**Comment by mananwason** [comment]
@codethejason As far as I can see, the page still redirects to the blogs. Is this correct?

**Comment by codethejason** [comment]
@mananwason Hmm, that seems to be a bug. The page should redirect to the blog text, which also has a link to the blog.

**Comment by mananwason** [comment]
okay then I'll merge this and create an issue for the bug.

**Pull request merged**
