### PR TITLE
Adding my info.

### PR DESCRIPTION
**Pull request by mercuryprasad**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://mercuryprasad.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@mercuryprasad Squash commits pls.

**Comment by mercuryprasad** [comment]
Please elaborate.

**Comment by Yathannsh** [comment]
@mercuryprasad  refer [this](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md#squashing-commits)!

**Comment by Yathannsh** [comment]
@mercuryprasad  read [this](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md#squashing-commits)!

**Comment by mercuryprasad** [comment]
HI I am not able to squash the commit. Tell me one alternate method.

**Pull request closed without merging**
