### PR TITLE
Social Media Buttons

### PR DESCRIPTION
**Pull request by ghost**
I have added some new effects again and some spacing between the social media buttons.

### CODE REVIEW

**Comment by Meta-Maxim** [comment]
@michaeljancen  Whoa you should squash all those commits. You somehow managed to push the whole commit history. Also I don't see which commit added the new features, only your member data.

**Comment by michaeljancen** [comment]
Ups was it me? :/ Sorry I am new to GitHub, please tell me how I can fix that.

**Comment by Meta-Maxim** [comment]
Uh, ok first of all don¹t use multiple pull requests for the same thing.
Pull requests can be updated, so theres no need to make a pull with a new
feature and then another one with an update to that feature. So close the
outdated pull. You can squash (combine several commits) before you push,
google how to do that, theres plenty of tutorials.

If you need to squash commits in a pull request, it's a bit harder, heres what I use:
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

If you didn¹t make too many changes, it can be easier for now to just close
the two pull requests, clone a clean copy of the repo, add your changes back
into it, and commit once and request a fresh pull with only that commit in
it.

**Comment by MarioScappini** [comment]
Sorry, but did I messed up or it wasn't my fault?

2015-12-18 23:05 GMT-03:00 Max Borsch notifications@github.com:

**Comment by MaxBorsch** [comment]
Well, I guess you could say you messed up. You used two pulls for the same thing, and also the pull request has everything committed in it instead of just your changes.

**Comment by Meta-Maxim** [comment]
@MarioScappini Oh sorry not you, the creator of this pull.

**Comment by MarioScappini** [comment]
That was because first I got an task, which consited in re-desing the
website, so I did it, but later they told me because there were having
issues with the repositories they decided to change that task, so thats why
i made two pull request, any ideas how I should solve this?

2015-12-18 23:10 GMT-03:00 Max Borsch notifications@github.com:

**Comment by MarioScappini** [comment]
Oh, ok... :)

2015-12-18 23:14 GMT-03:00 Mario Scappini makio.scappini@gmail.com:

**Comment by ghost** [comment]
@MaxBorsch thank you I will do that.

**Pull request merged**
