### PR TITLE
updated index.html

### PR DESCRIPTION
**Pull request by AvramPop**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://AvramPop.github.io/gci15.fossasia.org

**Comment by prwatch** [comment]
DEMO: http://AvramPop.github.io/gci15.fossasia.org

**Comment by AvramPop** [comment]
ive used the syntax used in the other projects in gallery but for mine the photo does not appear

**Comment by mananwason** [comment]
@AvramPop Your image is already there !!
screen shot 2016-01-10 at 7 02 18 pm

**Comment by mananwason** [comment]
@AvramPop I believe it is due to the size of the image. Could you optimise it?

**Comment by jigyasa-grover** [comment]
@AvramPop Working on this ?

**Comment by AvramPop** [comment]
i'm going to fix this tonight. im sorry but i was very busy with school

```
On Wednesday, 13 January 2016, 15:20, Jigyasa Grover <notifications@github.com> wrote:
```

 @AvramPop Working on this ?—

**Comment by jigyasa-grover** [comment]
Sure.

**Comment by AvramPop** [comment]
is it ok now?

**Comment by jigyasa-grover** [comment]
@AvramPop Resolve merge conflicts .

**Pull request closed without merging**
