### PR TITLE
Fixed the indent of students.yml and added new student info

### PR DESCRIPTION
**Pull request by seadog007**

### CODE REVIEW

**Comment by mariobehling** [comment]
@seadog007 Good work, but because of the previous merge, it has conflicts. Please also provide a link to your demo site. Thanks for resolving conflicts!

**Comment by seadog007** [comment]
@mariobehling OK, there is the test site, http://seadog007.github.io/gci15.fossasia.org/

**Comment by mariobehling** [comment]
Excellent job! What is the link to the GCI issue?

**Comment by seadog007** [comment]
@mariobehling I didn't claim it yet, because I am waiting for review of previous task
by the way, the link of fifth step is wrong in the task https://codein.withgoogle.com/tasks/4586431058018304/

**Comment by mariobehling** [comment]
Ok, thanks corrected it. What is the link to your task, that has not been accepted yet?

**Comment by seadog007** [comment]
My current task is this, https://codein.withgoogle.com/dashboard/task-instances/5914901537095680/

**Pull request merged**
