### PR TITLE
Added Myself (Yash Verma)

### PR DESCRIPTION
**Pull request by YashKumarVerma**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://YashKumarVerma.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@YashKumarVerma Squash commits.

**Comment by YashKumarVerma** [comment]
mam,  but can you please give me link of tutorial to do so ?

**Comment by jigyasa-grover** [comment]
Refer this: https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md

**Comment by YashKumarVerma** [comment]
can'i do do it using desktop app

**Comment by mananwason** [comment]
@YashKumarVerma You need to use command line for this.

**Comment by mananwason** [comment]
Or else you can close this PR, delete fork, then refork and add a single commit

**Pull request closed without merging**
