### PR TITLE
Added 12 mentors

### PR DESCRIPTION
**Pull request by shiftsayan**
I have added pictures, names and links of 12 mentors. Working on issue 397.

Here is the list:
Jan Suhr
Duke Leto
Iwan Gabovitch
Kalpa Welivitigoda
Lisa Hui
Manan Wason
Rafał Kowalski
Samarjeet
Sambuddha Basu
Tymon Radzik
Anh-Tu Nguyen
Michael Peter Christen

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://shiftsayan.github.io/gci15.fossasia.org

**Comment by jig08** [comment]
@shiftsayan Check the mentors included already wrt Issue #397

**Comment by shiftsayan** [comment]
@jig08 I am unable to check the mentors I have included in the list. I guess I do not have the required permissions.

However, I am working on #397 and am keeping a tally that none are repeated or left out.

**Comment by jigyasa-grover** [comment]
Okay ! I shall check them out then.

**Pull request merged**
