### PR TITLE
Added section issues. Solves issue #559

### PR DESCRIPTION
**Pull request by abishekvashok**
Added issue's section as part of GCI task to resolve issue #559. Hurray :)

And here's the link to my task: https://codein.withgoogle.com/dashboard/task-instances/6099260126789632/?sp-page=1

Please accept soon before conflicts arrise @mananwason @jig08 @mariobehling @roonyh.
- Last working days enjoying at GCI

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
Looks fine now :smile:

**Comment by abishekvashok** [comment]
Thanks @mananwason those where crucial points would be working without sleeping today so anybody of you gotta stay awake as I gonna complete tasks in flash. [maybe mentors in other time-zones but I see you are really active and the greatest sir, really respecting, saluting you sir also to @jig08 , @mariobehling , @roonyh , @SaptakS you all have done a wonderfull job it was a pleasure for meeting you all].

**Comment by mananwason** [comment]
Great @Abhi2424shek. All the best :+1:

**Pull request merged**
