### PR TITLE
Solved issue to add games section in fossasisa Google-codein website as a part of the task at GCI

### PR DESCRIPTION
**Pull request by abishekvashok**
Managed to solve the issue to add games section in fossasisa Google-codein website as a part of the task at GCI

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by abishekvashok** [comment]
I done it please accept it, you know it's been some time

**Comment by SaptakS** [comment]
Firstly stash all your commits. Secondly, I think the design for the dropdown isn't going with the website.

**Comment by abishekvashok** [comment]
Can I do it online?

**Comment by abishekvashok** [comment]
Ok wait I am squashing them offline with GitHub for desktop wait till I clone the repo

**Comment by SaptakS** [comment]
OK cool..

**Comment by abishekvashok** [comment]
Please approve the Added the Games Section commit link: https://github.com/Abhi2424shek/gci15.fossasia.org/commit/bed60ace3541fa85e5e8642b942214837c2e6859 and also remove the other commits

**Comment by mananwason** [comment]
@Abhi2424shek You need to do that!!

**Comment by mananwason** [comment]
You can refer to https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md

**Comment by yasoob** [comment]
And now there are merge conflicts which need to be resolved. @Abhi2424shek kindly resolve the merge conflicts as well.

**Pull request closed without merging**
