### PR TITLE
Changed hover animation of social media icon

### PR DESCRIPTION
**Pull request by JLeow00**
My mentor saptaks said that the social media icons' displacement effect seemed out of place, so I changed it to a box shadow effect. I also added color to the email icon on hover to make the box effect more prominent

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://JLeow00.github.io/gci15.fossasia.org

**Comment by SaptakS** [comment]
@JLeow00 the hover effect on FB icon appears to be slightly different than the other icons.. It seems to first change to a lighter blue and then to the darker blue...While in other icons it changes to a single color. Please check..

**Comment by JLeow00** [comment]
Its due to the goof class attached to the facebook icon. Removing the class from the facebook icon removes this color changing behavior. Should I remove the goof class to fix this behavior?

Edit: goof not poof

**Comment by mananwason** [comment]
@JLeow00 Please squash commits as well. Find instructions here https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md

**Comment by JLeow00** [comment]
@mananwason Done, is it alright?

**Comment by mananwason** [comment]
@JLeow00 I believe you didn't remove other commit messages while squashing. Please edit the commit message, then we can merge.
screen shot 2015-12-27 at 12 54 24 pm

**Comment by JLeow00** [comment]
@mananwason Done. Anything else?

**Comment by mananwason** [comment]
Awesome !! Merging :smile:

**Pull request merged**
