### PR TITLE
minified a bunch of code

### PR DESCRIPTION
**Pull request by jmurzaku**
Minified a bunch of code to make site faster #700

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://JamMurz.github.io/gci15.fossasia.org

**Comment by jmurzaku** [comment]
@yasoob here i made a new pull request because i accidentally deleted my other :smile:

**Comment by prwatch** [comment]
DEMO: http://JamMurz.github.io/gci15.fossasia.org

**Comment by abishekvashok** [comment]
@JamMurz you could always re-open the PR. And I never told that your work was bad and it was not good or rubbish. Just letting you knwo that you could do more. :smiley:

**Comment by jmurzaku** [comment]
@Abhi2424shek I accidentally deleted the other branch so I couldn't reopen that other one. Thanks for your tips though :smile:

**Comment by abishekvashok** [comment]
@JamMurz welcome as always. Do you want me to delete my comments so as to keep the issue clean?

**Comment by jmurzaku** [comment]
@Abhi2424shek no keep them so I don't forget :)

**Comment by prwatch** [comment]
DEMO: http://JamMurz.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@JamMurz Can you resolve conflicts and keep the stuff @Abhi2424shek has added in #716. It has apparently improved the speed a lot. We can see what happens and merge thisthen. Cheers :smile:

**Comment by jmurzaku** [comment]
@mananwason ill close this PR because it has almost the same things @Abhi2424shek had in his. :+1:

**Comment by Abhi2424shek** [comment]
@JamMurz hey man I never did anything you did. :) :smiley:

**Comment by mananwason** [comment]
Oh okay great @JamMurz :+1: Thanks for contributing :smile:

**Pull request closed without merging**
