### PR TITLE
Added a mentor as a part of GCI

### PR DESCRIPTION
**Pull request by abishekvashok**
Added some mentors as a part of task in GCI for FOSSASIA. Hope you'd accept this PR soon enough. :) Here's the link to my task: https://codein.withgoogle.com/dashboard/task-instances/6273948341764096/?sp-page=1 . Please review it soon @jig08 @roonyh @sudheesh001 @SaptakS @niccokunzmann @mananwason .

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@SaptakS Please check the changes before merging. 

@Abhi2424shek @SaptakS You have added facebook details of the previous mentor for the one you added now. Please fix it.

**Comment by abishekvashok** [comment]
Ok let's try squashing right @mananwason here's the commands:

git add .
git rebase -i HEAD~2

Then the pop up displays and I replaced the second pick with squash and saved and exited.
Then another pop up displays I commented out everything except the needed title.
What to do next? @mananwason

The output is:
 Sucessfully reabsed and updated ...

**Comment by roonyh** [comment]
Save and exit.

Then see the output of `git status` and `git log` to make sure everything worked.

**Comment by abishekvashok** [comment]
yes! :) Hurray. Thanks all for that but no commits are here the commit is https://github.com/Abhi2424shek/gci15.fossasia.org/commit/fbdcabfc6e25e3508cde1ee9397ae18d5104ffbc @roonyh  Wanna me to create a new PR as this is merged! :( :)

**Comment by roonyh** [comment]
yes. make a new PR

**Comment by Abhi2424shek** [comment]
but it's having merge conflicts (should I reclone and re-fork) @roonyh

**Comment by abishekvashok** [comment]
@roonyh here's the PR: https://github.com/fossasia/gci15.fossasia.org/pull/539 .Really sorry for all that I have done, really (as I just did a few mistakes by misplacing the info) :(

**Comment by SaptakS** [comment]
@mananwason ... completely overlooked that.. Sorry..

**Comment by abishekvashok** [comment]
Anyone having a bad impression  on me ? :)

**Pull request merged**
