### PR TITLE
Fixed #140

### LINKED ISSUE #140: Reduce slider image sizes
I can see some work is being done in #121 regarding page speed. Shall we start with reducing images sizes in the slider. Its fine even if we lose the quality because some images are just huge. For example [this one](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/img/community.jpg) is 2.7MB! If someone is already upto this feel free to loose some quality.

### PR DESCRIPTION
**Pull request by Yathannsh**
This fixes #140 , by optimizing the slider's images.
[Demo](http://yathannsh.github.io/gci15.fossasia.org/)

### CODE REVIEW

**Comment by PiotrKowalski** [comment]
Can't you squash it? Squashing 2 commits isn't really hard, ;P

**Comment by Yathannsh** [comment]
@PiotrKowalski , yes I considered that. xD 
But the thing is I have changed dimensions as well.
 Now if a problem shall arise it will be convenient to revert to the commit where images where optimized but not re-sized. If you still think squashing is a better way, let me know!

**Comment by PiotrKowalski** [comment]
is _site really needed? I think that it was deleted a few days ago from repo

**Comment by Yathannsh** [comment]
It's still there @PiotrKowalski  :)
erf

**Comment by roonyh** [comment]
Shall we add `_site` to `.gitignore`? There is no reason to keep it in the repo at the moment right?

**Comment by Yathannsh** [comment]
Yes, _site is auto generated when the site is rendered. 
Adding it to .gitignore should work the best, I suppose @roonyh!

**Comment by roonyh** [comment]
Lets merge this and then you go ahead and submit a pr adding it to .gitignore. If we use any jekyll pluggins at some we point we will get it back.

**Comment by Yathannsh** [comment]
I see <code>_site</code> in .gitignore already. 
Can't figure out why it isn't working. Could you help me figuring it out? @roonyh

**Comment by roonyh** [comment]
@Yathannsh try [this](http://stackoverflow.com/questions/1274057/making-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore)

**Comment by Yathannsh** [comment]
Thanks @roonyh! :D
This solves it I I suppose. Implemented a cache remove and sent a PR!

**Pull request merged**
