### PR TITLE
Updated li.dimer hover transition css

### PR DESCRIPTION
**Pull request by yasoob**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://yasoob.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@yasoob No visible changes in the section. If you could point out the changes through a gif, it would be nice. Thanks!

**Comment by yasoob** [comment]
@mananwason Currently if you hover-over the "[View Blog Posts](http://gci15.fossasia.org/#dimer)" link in the `blog_posts` section there is a smooth transition. But if you move your mouse away from the link the `hover-out` transition appears abrupt. Their is no transition because the `transition:1s` is being applied on `.dimer:hover` and not on `.dimer`.

I hope this clarifies the issue :smile:

**Comment by mananwason** [comment]
Oh yeah!! Didn't notice that :smile:

**Comment by yasoob** [comment]
Well I can't blame you. The change was subtle :+1:

**Comment by mananwason** [comment]
:stuck_out_tongue:

**Pull request merged**
