### PR TITLE
Added Games section and resolved the issue to add Games section

### PR DESCRIPTION
**Pull request by abishekvashok**
Added Games section and resolved the issue to add Games section as a part of GCI task @sudheesh001  @mariobehling . Please accept it it has only one commit

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by abishekvashok** [comment]
Please merge it all checks are passed!!!

**Comment by abishekvashok** [comment]
@roonyh atleast someone help out quickly @nikunjness @sudheesh001 @mariobehling

**Comment by roonyh** [comment]
The left right arrows looks better than the dots we have now. Thanks for those!

Shouldn't there be a title or some way to show that the section contains **Games**? At the moment it says View Gallery.

Plus I found a bug. Try keeping both galleries open and clicking on arrows in the games section. When I tried, it moved items of both sections.

A little git tip: When you fix above and when you commit the changes you can use ammending to avoid adding more commits. `git commit --amend`

And It looks like you are too anxious to get something in and close the task. This is not unexpected in a competition. But if you calmed down a bit and try to submit a quality work, after trying out your work a bit and fixing obvious bugs, everything would be much smoother. You will even enjoy your work more!

**Comment by abishekvashok** [comment]
I would delete this and add a new pull request my terminal isn't working well squashing and another commit is added! Please see the codein page

**Pull request closed without merging**
