### PR TITLE
Poh Say Keong's blog post

### PR DESCRIPTION
**Pull request by PohSayKeong**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://PohSayKeong.github.io/gci15.fossasia.org

**Comment by jig08** [comment]
Squash commits pls ?

**Comment by mananwason** [comment]
@PohSayKeong Please remove the merge tracking commit. @jig08 can't squash em, can he? :stuck_out_tongue_winking_eye:

**Comment by jigyasa-grover** [comment]
My bad.

**Comment by PohSayKeong** [comment]
Sorry, but may I ask how I can do that?

**Comment by pythad** [comment]
@PohSayKeong , take a look at [this page](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) ;)

**Comment by PohSayKeong** [comment]
Sorry, but I did it the long way, so I will be closing this, I have created a new pull request on the other side.

**Pull request closed without merging**
