### PR TITLE
 Fixed #198

### LINKED ISSUE #198: Thank-You scroll doesn't display the German translation
The current website, has a German translation for Thank-You but it is not displayed as the keyframe styles were not changed whilst it was added.
 Also the reverse scroll is way too hazy, but should look great if it is changed the way @roonyh  suggested in #159

### PR DESCRIPTION
**Pull request by Yathannsh**
This fixes #198 by extending the keyframes and incorporating the transition suggested by @roonyh 
[DEMO](http://yathannsh.github.io/gci15.fossasia.org/)

### CODE REVIEW

**Comment by roonyh** [comment]
I think we will need a more permanent fix involving js. This makes the last line move slower than the rest. And we need to keep changing css when adding new translations don't we?

**Comment by Yathannsh** [comment]
Yes, we would need to modify the CSS each time a new great is added. 
A Js fix, sounds great! I have implemented one let me know if it will suffice.

**Comment by Yathannsh** [comment]
@roonyh ,added a Js based scroll! 
Check it out: [Demo](http://yathannsh.github.io/gci15.fossasia.org/)

**Comment by mananwason** [comment]
@Yathannsh looks good. Just squash the commits and then you're all set.

**Comment by Yathannsh** [comment]
@mananwason , commits squashed!

**Comment by mananwason** [comment]
Awesome @Yathannsh. Merged !!

**Pull request merged**
