### PR TITLE
Added screenshot to img folder

### PR DESCRIPTION
**Pull request by nicholascheow**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://nicholascheow.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@nicholascheow Please squash commits. Thanks!

**Comment by mananwason** [comment]
You can refer to [this](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md)

**Comment by nicholascheow** [comment]
I did squash them. Was it successful

**Comment by mananwason** [comment]
No @nicholascheow. Did you force push after rebasing? command : `git push origin gh-pages -f`

**Comment by nicholascheow** [comment]
thanks. I just ran that command
Counting objects: 11, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (11/11), done.
Writing objects: 100% (11/11), 25.44 KiB | 0 bytes/s, done.
Total 11 (delta 7), reused 0 (delta 0)
To https://github.com/nicholascheow/gci15.fossasia.org.git
- 8ef2ac3...33a8b83 gh-pages -> gh-pages (forced update)

**Comment by nicholascheow** [comment]
I apologise for this being my first time running a PR

**Comment by mananwason** [comment]
@nicholascheow Still not done. Can you please follow the guide exactly. First, please run `git log` and post the output first. Cheers!

**Comment by nicholascheow** [comment]
C:\Users\Nicholas\Desktop\gci15.fossasia.org [gh-pages|REBASE-i +1 ~0 -0 !]> git log
commit ee300cc86f25287eb063930b48f90ddb55ec4216
Merge: 2efe598 1cbaf5d
Author: Jigyasa Grover grover.jigyasa1@gmail.com
Date:   Mon Jan 25 09:35:01 2016 +0530

```
Merge pull request #674 from JamMurz/gh-pages

Improved lights out section
```

commit 2efe5987f7c65509dea131c910a68f375005311a
Merge: 015d3ae 7aec7ab
Author: Jigyasa Grover grover.jigyasa1@gmail.com
Date:   Mon Jan 25 09:33:57 2016 +0530

```
Merge pull request #677 from mattpdl/gh-pages

GCI Task
```

commit 1cbaf5dc8811395039e70800a68811694a9060c4
Author: John Murzaku jam@lissus.com
Date:   Sun Jan 24 15:17:35 2016 -0500

```
Improved lights out section
```

commit 7aec7ab3a967fbcd14532429dd3366f64a96b69b
Author: Matthew Ponce de Leon mattpdl01@gmail.com
Date:   Sun Jan 24 13:06:32 2016 -0800

```
Add image and credentials
```

commit 015d3aeeea00854dcf49efb4bf3357c9edc42c5c
Merge: b6f546e a677967
Author: Manan Wason manan13056@iiitd.ac.in
Date:   Mon Jan 25 01:21:05 2016 +0530

```
Merge pull request #672 from yasoob/gh-pages

Reduced gallery image sizes to 240x240
```

commit a6779677edf7ee85b328a5a87da0ce5704fcb45e
Author: M.Yasoob Ullah Khalid ☺ yasoob.khld@gmail.com
Date:   Mon Jan 25 00:39:13 2016 +0500

```
Reduced gallery image sizes to 240x240 :boom:
```

commit b6f546ec4ead10e5c92c4e3ddaf18d293a7d9c05
Merge: c5606ed e103ec3
Author: Manan Wason manan13056@iiitd.ac.in
Date:   Mon Jan 25 01:05:43 2016 +0530
:

**Comment by mananwason** [comment]
Where are your commits here? I can't see them :confused:

**Comment by nicholascheow** [comment]
Alright. Would you like me to try again from the start by making the commits?

**Comment by nicholascheow** [comment]
And thank you for your patience

**Comment by mananwason** [comment]
Sure @nicholascheow !! I suggest you delete your local copy and clone it from your fork again. Then tell me the output of `git log`. Then we can proceed from there. Cheers!

**Pull request closed without merging**
