### PR TITLE
Added Myself (Yash Verma)

### PR DESCRIPTION
**Pull request by YashKumarVerma**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://YashKumarVerma.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@YashKumarVerma You haven't added details in `index.html`

**Comment by YashKumarVerma** [comment]
oh !

**Comment by jigyasa-grover** [comment]
Hey @YashKumarVerma , Were you able to sort things out ? :)
And also resolve merge conflicts. [This](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) might help.

**Comment by jigyasa-grover** [comment]
Are you still working on this @YashKumarVerma ?

**Pull request closed without merging**
