### PR TITLE
changed footer for social icons

### PR DESCRIPTION
**Pull request by shiftsayan**
Added the new G+ icon and redesigned the footer.

### CODE REVIEW

**Comment by mananwason** [comment]
What is this commit doing @shiftsayan

**Comment by shiftsayan** [comment]
In my 4 most recent commits, I have:
1) sorted the G+ icon issue
2) modified the footer with link to Flickr as well
3) added three languages to Thank You column

**Comment by mananwason** [comment]
Please add some description in all the PR's.

**Comment by jigyasa-grover** [comment]
I believe the G+ Icon for mobiles #144 and Flickr icon #233 was resolved.

**Comment by jigyasa-grover** [comment]
PR #234 Flickr icon updated.

**Comment by shiftsayan** [comment]
This changes the Google+ logo to the latest Google release and makes the design of the footer more seamless.

**Comment by shiftsayan** [comment]
The issue has been resolved for the CSS file. Please merge!

**Comment by mananwason** [comment]
@shiftsayan Please edit the commit message to something more meaningful and please remove the merge request as well, then we can merge.

**Comment by shiftsayan** [comment]
I hope this sorts it. Thanks!

**Comment by mananwason** [comment]
@shiftsayan you have 8 commits in this PR, please look at the GIT.md file in the main repository that can guide you on how to squash commits into one and remove the merge commits.

**Comment by SaptakS** [comment]
This branch also has some conflicts it seems. Please resolve that..

**Pull request closed without merging**
