### PR TITLE
Added my work to gallery

### PR DESCRIPTION
**Pull request by Elgayar**
Added two screenshots in the student gallery, one for my php app and one
for my lights out javascript app.
Then added the pieces of code in index.html to make them appear! :)

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Elgayar.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@Elgayar Shift your `Lights Out` project to the dedicated `Lights Out` section and leave the other in the `Gallery` ?

**Comment by Elgayar** [comment]
Done! @jig08 Sorry I missed that :dancer:

**Comment by jigyasa-grover** [comment]
No issues :)
Squash your commits and we are all set to merge. Refer [this](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) for help.

**Comment by Elgayar** [comment]
Done!!! :dancer: @jig08 :laughing:

**Comment by jigyasa-grover** [comment]
Awesome @Elgayar :v:

**Comment by Elgayar** [comment]
Thanks a lot!! :heart_decoration:

**Pull request merged**
