### PR TITLE
Fixed #104 #110 #103 #84

### LINKED ISSUE #84: Icons turn into white
If people open the link in a new tab, then the icons turn into white.

It only happen on FF

### LINKED ISSUE #103: Error padding in footer section

### LINKED ISSUE #104: Bad looking slideshow on mobile phones
Slides titles are white so it looks bad on mobile phones if background is white.
screenshot_2015-12-20-13-38-04_1450615137439
screenshot_2015-12-20-13-38-16_1450615174958

If background is dark it is good - 
screenshot_2015-12-20-13-38-11_1450615160470

### LINKED ISSUE #110: Not all social links have hover effects.
Github both hover and not hover effects are black.
Stackexchange and Instagram have no hover effects at all.
It would be nice if someone implemented it.

### PR DESCRIPTION
**Pull request by Yathannsh**
Simple property fix; the slider text is now visible even on mobile devices, which fixes #104 
Also added and fixed hover effects of all social icons available, which fixes #110 
Changed the bottom padding for visibility, which fixes #103 
^This fix has been removed as @seadog007 had a better solution to this problem
Changed the visited property of github icon, which fixes #84 
[Demo](http://yathannsh.github.io/gci15.fossasia.org/)

### CODE REVIEW

**Comment by seadog007** [comment]
well, you didn't fix #103. You just added some space under the foot, and also I fixed #103 in #105.

In your repo, it look like this

**Comment by Yathannsh** [comment]
@seadog007 , well adding space makes the text visible and solves the problem right?
Whilst you have made the text vertically aligned in the middle,  I thought about keeping it near the bottom.  Anyway, sorry about solving it after you fixed it; as your issue was, and still is on the issue section thought about applying my fix! :)

**Comment by Yathannsh** [comment]
@seadog007 , well adding space makes the text visible and solves the problem right?
Whilst you have made the text vertically aligned in the middle, I thought about keeping it near the bottom. Anyway, sorry about solving #103  after you fixed it; as your issue was, and still is on the issue section I assumed it wasn't fixed. Therefore, thought about applying my fix! :)

**Comment by seadog007** [comment]
First, well, maybe we need to vote for which design is better. And also, if you ask you friend who has design major, I 99% sure they will tell you that you need some space between the contents and the edges
Second, the issue #103 still exist in your fix, because the right part still stick to the bottom edge.

**Comment by Yathannsh** [comment]
@seadog007 , I don't have a friend who has a designing major xD 
Though adding some space solves the visibility problem,I think maybe implementing your solution of  vertically aligning it in the middle will make it look better!
As I can't close this pull request because it contains  fixes for other three issues, should I replace my technique and incorporate yours? Let's not fight about whose design is better and do what will make the website look  better. I am ready to incorporate your fix and site credit   to you if its alright with you :)
If you think there's any other way to solve this let me know! Thanks!

**Comment by seadog007** [comment]
oh, you can just remove the commit afdd5fd.

``` bash
cd the_rootdir_of_this_repo
git reset HEAD^^
git checkout stylesheets/stylesheet.css
git commit -am "Fixed the problem of github icon turning white after visit"
git push -f
```

**Comment by Yathannsh** [comment]
@seadog007 , that reset was removing the fix for #84  but anyway, now your fix can  be incorporated as I deleted that commit. :)

**Comment by seadog007** [comment]
Yep, thank. And I know it will removing the fix for #84,
so I add `git commit -am "Fixed the problem of github icon turning white after visit"`, isn't it work? :/

**Comment by Yathannsh** [comment]
Yes, did that and added the fix for #84 again^

**Comment by harshkothari410** [comment]
All looks good. But there is problem with Footer. Need some margin. Check it out

**Comment by Yathannsh** [comment]
@harshkothari410  , fixed it!

**Comment by harshkothari410** [comment]
Looks good.

**Pull request merged**
