### PR TITLE
i added my image and details 

### PR DESCRIPTION
**Pull request by rohythakur**
I have added my image and details .

### CODE REVIEW

**Comment by tradzik** [comment]
looks fine, thanks. Can you [squash your commits](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) into one? It improves readability.

**Comment by PiotrKowalski** [comment]
Please squash your commits. I know it is hard. I've got problems with that but try do it ;)
Tradzik: nice timing :P

**Comment by rohythakur** [comment]
OK I will do that can you tell me how can I do that

**Comment by tradzik** [comment]
@rohythakur I sent you a link in my post. Believe me - it is not so hard.

**Comment by rohythakur** [comment]
I have tried to do that and I also I learned how to do that but problem is
that there are lot of other commits between my two commits so this is
arising a problem when I am trying to squash the two commits into one, can
you provide me solutions for that

**Pull request closed without merging**
