### PR TITLE
Add my blog post

### PR DESCRIPTION
**Pull request by sevazhidkov**

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
@sevazhidkov  Squash your commits.

**Comment by sevazhidkov** [comment]
@jig08 Done

**Comment by jigyasa-grover** [comment]
And now there are merge conflicts in this, resolve 'em ?

**Comment by sevazhidkov** [comment]
@jig08 Done

**Comment by mananwason** [comment]
@sevazhidkov You need to squash the commits as well, then we can merge. Cheers!

**Comment by sevazhidkov** [comment]
I tried to, but I can't squash commit with resolving merge conflict. I see it in `git log`:

```
iMac-Mac:gci15.fossasia.org mac$ git log
commit 56d3debd85ad353c78b1865e7886486776d075eb
Merge: d25ec6d 550148f
Author: Seva Zhidkov <zhidkovseva@gmail.com>
Date:   Sat Jan 23 11:03:08 2016 +0400

    Resolve merge conflict

commit 550148f949460b20f20e55d59453ea497f1140ba
commit 550148f949460b20f20e55d59453ea497f1140ba
Merge: 51c7a2d 1b344c5
Author: Jigyasa Grover <grover.jigyasa1@gmail.com>
Date:   Sat Jan 23 12:13:33 2016 +0530

    Merge pull request #594 from shiftsayan/gh-pages

    Added 2 blog posts

commit d25ec6d8c04c808cab687db822fae5c9a417ae81
Author: Seva Zhidkov <zhidkovseva@gmail.com>
Date:   Sat Jan 23 10:14:24 2016 +0400

    Add my blog post
```

But I don't see it in `git rebase -i HEAD~3`:

```

pick 92eca57 Added student Marcus
pick d25ec6d Add my blog post
pick 429b90a Add lights out project
pick 1b344c5 blogs

```

**Comment by mananwason** [comment]
@sevazhidkov Please do `git pull --rebase` and tell me if you're able to squash then. Cheers!

**Comment by codethejason** [comment]
@sevazhidkov You can reset from fossasia/gh-pages and use the guide [here](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/blogpost.md) to append  a blog post.

**Pull request closed without merging**
