### PR TITLE
#395 Separate Social Media area into area for each service and styling

### PR DESCRIPTION
**Pull request by aayusharora**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://aayusharora.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@aayusharora Could you resolve conflicts plus if we scroll through the sections, it is taking some time to render and it is rendering every time I go to a section. Could you check that out. Thanks!

**Comment by aayusharora** [comment]
@mananwason ,you are correct in both cases,first I was having merge conflicts ,what I hv done is cloning the repo ,fetching upstream,merging upstream,now I hv done my local changes manually ,pushed it,generated pull request ,is anything wrong in approach?

**Comment by aayusharora** [comment]
Also,I like to mention ,tweets can now have links active,which was one of the points for this issue.

**Comment by mariobehling** [comment]
Branch still has conflicts. Please resolve. Would be great to get this contribution in. Cheers.

**Comment by abishekvashok** [comment]
Please resolve the conflicts @aayusharora

**Comment by aayusharora** [comment]
@mariobehling ,@Abhi2424shek, I will do it :)

**Comment by aayusharora** [comment]
@mananwason ,@mariobehling can you check it now ?

**Comment by jigyasa-grover** [comment]
What happened to the `mentors` section in (1) ? It shows correctly in the original (2)
1. `http://aayusharora.github.io/gci15.fossasia.org/`
   screenshot from 2016-01-17 18 09 58
2. `http://gci15.fossasia.org/`
   screenshot from 2016-01-17 18 11 37

**Comment by abishekvashok** [comment]
@aayusharora  please resolve the conflict and never remove the " --- --- " code at the start of the index file, it is necessary for Jekyll. Please work out man! and lastly the merge conflict, got it :)

**Comment by yasoob** [comment]
Hey @Abhi2424shek I am sorry to chime in again but please do not repeat what the mentors have already commented about (like the merge conflicts). It just adds noise to the original discussion. If you have something concrete to comment about, only then go ahead and comment :+1: Cheers!

**Comment by abishekvashok** [comment]
@yasoob  no on here mentioned about the "--- ---" Lines here!

**Comment by jigyasa-grover** [comment]
@aayusharora Refer [this](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) for help .

**Comment by aayusharora** [comment]
ok,thanks @jig08 ,I will do it .

**Comment by jigyasa-grover** [comment]
Seems to be fine for now, wrt issue #395 .

**Pull request closed without merging**
