### PR TITLE
Re-Construction of photo folders, and fixed the path of default photo

### PR DESCRIPTION
**Pull request by seadog007**

### CODE REVIEW

**Comment by seadog007** [comment]
well, there is a new photo.....

**Comment by seadog007** [comment]
There is the demo site, http://seadog007.github.io/gci15.fossasia.org/

**Comment by seadog007** [comment]
@mariobehling You can merge other two PR first, and I will solve the conflicts :P

**Comment by seadog007** [comment]
OK, fine, there is no conflict XD

**Comment by mariobehling** [comment]
Yeah, very good. By the way, if you have some ideas for cool features for the site, please add them in the issue tracker. Cheers!

**Pull request merged**
