### PR TITLE
Add 5 blog posts

### PR DESCRIPTION
**Pull request by YagoGG**
This PR includes the following blog posts:

[**Fossasia - Codein Organiser**](http://codein-dwij.github.io/blog_hugo/post/fossasia/), by Dwij Jha (@codein-dwij)
[**What Open Source Is For Me**](http://juanvulcano.github.io/post/What-open-source-is-for-me/), by Juan F. Verhook (@juanvulcano)
[**How to setup a blog using Hugo**](https://poprosturonin.github.io/post/setupHugo/), by Bartosz Wiśniewski (@poprosturonin)
[**Starting with Jekyll**](http://sayanchaudhry.me/blog/jekyll/2015/12/29/getting-started-with-jekyll.markdown.html), by by Sayan Chaudhry (@shiftsayan)
[**Google Code-in 2015/16**](http://yagogg.github.io/blog/google-code-in-2015/16/), by Yago González (@YagoGG)

And also uses a loseless compression in some of the thumbnails, for improved loading speed.

Thanks to the original authors of the posts!

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://YagoGG.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
Looks fine @YagoGG. We can merge :grinning:

**Comment by YagoGG** [comment]
Thanks @mananwason!

**Comment by mananwason** [comment]
Sure :smile: @YagoGG

**Pull request merged**
