### PR TITLE
Added the member section & a navigation bar 

### PR DESCRIPTION
**Pull request by Yathannsh**
# Updated Website
## Summary

Utilized bootstrap to add sections for student members and mentor member.
Also added a completely responsive navigation bar which corresponds to the design aesthetic. 
## Features
- Built on Bootstrap, hence completely responsive. 
-  Contains 2 sections : Mentors & Students  
-  Added empty containers for members to make use of. 
- Added overlays with contact links.  
- Added a navigation  Bar
- Contains  animated and responsive Member containers 
- The design strictly follows the design aesthetic.
- Added custom chrome header for chrome users.

### CODE REVIEW

**Comment by mariobehling** [comment]
"This branch has conflicts that must be resolved". Please merge with the work of Max and add your photo first. Let's go step by step with smaller changes.

**Comment by Yathannsh** [comment]
Sure, added my details and sent a PR :)

**Comment by mariobehling** [comment]
I am closing this then.

**Comment by mariobehling** [comment]
Please submit your task for review.

**Comment by Yathannsh** [comment]
@mariobehling , I have submitted for review.
Now, that I have merged with Max's work  should I integrate my work and send a PR or let it be?

**Comment by mariobehling** [comment]
Please check out this task. I think it suits you https://codein.withgoogle.com/tasks/5159210631299072/?sp-organization=4625502878826496

**Comment by Yathannsh** [comment]
Perfect, thanks!

**Pull request closed without merging**
