### PR TITLE
Fixed styling issues #567

### PR DESCRIPTION
**Pull request by jmurzaku**
fixed issue #567

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://JamMurz.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
Looks good @JamMurz. I believe you've taken into consideration, all the points put forward by @yasoob in #529. So, I am merging this. Cheers!

**Comment by jmurzaku** [comment]
@mananwason thanks! and also thanks @yasoob for the points :+1:

**Comment by mananwason** [comment]
:+1:

**Pull request merged**
