### PR TITLE
Address issue #375

### PR DESCRIPTION
**Pull request by mbj36**
@roonyh 

Now its look good :)

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://mbj36.github.io/gci15.fossasia.org

**Comment by roonyh** [comment]
Please organize the html with proper indentation. It looks all over the place at the moment. https://github.com/fossasia/gci15.fossasia.org/pull/388/files

This is better but I think this section should be highlighted and should have its own place. Please put a little more effort into it. Put it in a different row with a different background. You can be creative with the css.  

See the subscribe section from http://fossasia.org/. I am sure you have seen many better different examples.

Try to make something you are proud of!

**Comment by mbj36** [comment]
Okay :)
I will try my best

**Comment by abishekvashok** [comment]
All the best! Keep up the good work @mbj36

**Comment by jigyasa-grover** [comment]
@mbj36 Updates pls ?

**Comment by abishekvashok** [comment]
hey @jig08 give him some time! and the problem was that he left the "--- ---" at the top of the page blank

**Comment by jigyasa-grover** [comment]
@Abhi2424shek In my opinion asking for updates after 5 days is okay. Plus I never asked anyone to hurry up with their work :) I was just inquiring in case of any issues he is facing which could be helped with .

**Comment by abishekvashok** [comment]
@jig08 got it, just chill out! I never meant it that way :) :100:

**Comment by SaptakS** [comment]
@Abhi2424shek I gues @jig08  was just trying to know if he has some updates.. She was just trying to help him because there are too many PR open and it might result into merge conflicts later in which case he would have to do a lot more work... Also, his GCI task days might get over.. So keep it cool man... (Y)

**Comment by abishekvashok** [comment]
Hey now I am the culprit I was just joking right? @jig08 , I guess you all got a lot of humer @SaptakS . I was just trying to help out guys... Hope you'd take it in that sense man!

**Comment by mbj36** [comment]
i am closing this and in few hours i will be up with my work with new one

**Comment by jigyasa-grover** [comment]
Sure @mbj36 .

**Pull request closed without merging**
