### PR TITLE
New design

### PR DESCRIPTION
**Pull request by pythad**
Pull request which is ready to merge. I fixed collisions and used Max template system to implement the solution for links students and mentors.

I couldn't implement Max's navigation as it used bootstrap and it's too much to have 2 frameworks for 1 site, but I think we can work on it now.

 [Demo](http://pythad.github.io/gci15.fossasia.org/)

### CODE REVIEW

**Comment by mariobehling** [comment]
Does not display properly here for me.
screenshot from 2015-12-15 18 41 24

**Comment by pythad** [comment]
@mariobehling, the student hasn't submitted any photo. There is no photo at the main site also

**Comment by pythad** [comment]
@mariobehling, I made the site to render a default image if it doesn't exist.

**Comment by mariobehling** [comment]
Ok, great. Well, in regards to the framework. Can we stay with bootstrap, as it also was the initial tag? Then we can also keep the heading. Could you add the bottom with a first PR and your photo and add other features in following PRs?

**Comment by pythad** [comment]
@mariobehling, ahh, it had to be mentioned earlier... It' wasn't said that it had to use bootstrap only in the initial task about creating a website. I can't add the footer as it's a MaterializeCSS component, basically what Max did is forked my repo and added his elements and deleted MaterializeCSS so it's looks little ugly, but I think there are good Bootstrap components for this also and someone will implement it. I think I will just add my data, as rewriting all using Bootstrap will take a while, and I honestly I don't want to do this, just to exhausted working with MaterializeCSS and rewriting it for Bootstap seems stupid for me. Thank you for your suggestions, good luck!)

**Comment by mariobehling** [comment]
@pythad Sorry, it was a tag in the description. I think it was not mentioned clearly. My point is, as this is an effort for several students, it is difficult to work together if each student works in another way. Also, it makes it very difficult to avoid conflicts as there are constantly pull requests. I suggest, we sort this out step by step as small iterations. Maybe just add your photo and help to make it run? Here is a task that could be nice for you https://codein.withgoogle.com/tasks/4795004652355584/?sp-organization=4625502878826496

**Comment by pythad** [comment]
@mariobehling , yea, I understand you. I can see, so many PRs, it will be really hard to manage at the begging, probably I will wait some time and then contribute. It has to be organized somehow, maybe you need to add a notice in the task that one has to wait between pull requests and wait? It will be very hard to manage all these when the number of students increases.

**Comment by mariobehling** [comment]
Awesome, we really want to get you in. What we have seen from you is quality work. If you have ideas for tasks, that you would like to work on and that are easy to add into the page, please let me know. I would be happy to create a dedicated task for you. Happy to have you onboard!

**Pull request closed without merging**
