### PR TITLE
Improved speed by optimizing javascript,css and images as a part of issue #700

### PR DESCRIPTION
**Pull request by abishekvashok**
Improved speed by optimizing javascript,css and images for FOSSASIA with
the help of Google Page insights. I've commented the stats

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by abishekvashok** [comment]
See the stats here {It would improve some points after it is merged as the content then get's served via cloudflare} @jig08 @vicky002 @mananwason @roonyh @mariobehling @sudheesh001 

Stats of the PR {it would improve some more points after merging}
[abhi2424shek.github.io/gci15.fossasia.org]
image
image

And the current stats
[gci15.fossasia.org]
image
image

So mind merging them guys. - Happy coding, loving opensource

**Comment by vicky002** [comment]
This is huge change. We need to check all the JS and CSS files once.

**Comment by abishekvashok** [comment]
@vicky002 please :) and why not you make sure every code is working with help of developing tools on chrome and checking every actions and styles etc... Please do so. I am sure that I have'nt broken anything.

**Comment by vicky002** [comment]
@jig08 @mananwason Please check once.. this can be merged no issues.

**Comment by mananwason** [comment]
Great work @Abhi2424shek !! Thanks @vicky002 :smile:

**Pull request merged**
