### PR TITLE
Added Myself (Yash Verma) and my project with "thanks for contributing"

### PR DESCRIPTION
**Pull request by YashKumarVerma**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://YashKumarVerma.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@YashKumarVerma Resolve merge conflicts and squash them.

**Comment by YashKumarVerma** [comment]
there are no merge conflicts now

**Comment by mananwason** [comment]
@YashKumarVerma I see the merge conflicts right now as well. Please solve them and squash the commits into one. You can refer to [this](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md).

**Pull request closed without merging**
