### PR TITLE
Reduced page load time, improved speed.

### PR DESCRIPTION
**Pull request by abishekvashok**
Please see the stats which I commented @vicky002 @jig08 @mananwason @roonyh @mariobehling @sudheesh001

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by abishekvashok** [comment]
Here's the stats

Current GCI Website stats
[gci15.fossasia.org]
image
image

After my PR is merged {Please note that the speed will again increase after it's merged as then the content will be distributed by cloudflare}
[abhi2424shek.github.io/gci15.fossasia.org]
image
image

It's a great improvement for desktop/laptop users and there would be slight increase for speed to mobile users. So please review it guys.
- Happy coding

**Comment by jmurzaku** [comment]
Looks good! :+1:

**Comment by abishekvashok** [comment]
A quick look would be appreciated  guys - @roonyh @mariobehling @jig08 @sudheesh001 @mananwason

**Comment by roonyh** [comment]
Loading JS in the footer avoids blocking the rendering. I am not quite sure how Google page speed decides that the page is completed loading. Maybe it decides its completed once the page is rendered, while js is still not loaded? Since you are using `async` I think this is why you see the dramatic speed improvement.

So this makes the slider to not work until the slider images are all loaded. Which I think is a better user experience. All other small animations also won't happen until the html elements are all completely loaded right?

Anyway atm I think we should have this change.

Thanks @Abhi2424shek

**Comment by abishekvashok** [comment]
@roonyh  your's welcome. I you want the animations to be there, should I design a splash screen

**Comment by roonyh** [comment]
@Abhi2424shek Yeah that'd be nice!

**Comment by abishekvashok** [comment]
Ok @roonyh .

**Pull request merged**
