### PR TITLE
Improve speed #121

### PR DESCRIPTION
**Pull request by YagoGG**
The loading time has been significantly improved by:
- Cropping gallery's thumbnails
- Optimizing all images
- Removing unnecesary or unused files

[PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/) evaluation passed from a score of **16 to 47** in mobile speed, and from **6 to 58** in desktop (compared with the last commit at the moment of creating this PR, eeffc2f).

This problem has been referenced in issue #121.

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://YagoGG.github.io/gci15.fossasia.org

**Comment by roonyh** [comment]
This is really useful! Thanks much! :) Could you please resolve this conflicts?

**Comment by YagoGG** [comment]
Solved! Sorry, didn't realise about them ;)

**Comment by SaptakS** [comment]
Please stash all the commits into a single commit..

**Comment by mananwason** [comment]
@YagoGG You can find instructions for squashing here https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md

**Comment by roonyh** [comment]
@SaptakS @mananwason There are separate work done here though they all help improve page speed. Don't you thing they belong in separate commits? One huge single commit with all this work would not look nice imo. Except the first two, commits look fine to me. What do you think?

**Comment by SaptakS** [comment]
Yes.. What I meant was reduce the number of commits as much as suitable... Sorry for mentioning a single commit.. :)

**Comment by YagoGG** [comment]
So, should I squash ony the two first commits (ea46e4b, 64bf811) then?

**Comment by roonyh** [comment]
@SaptakS ah, no problem 😀 @YagoGG yep, works for me

**Comment by YagoGG** [comment]
This should squash both commits. Thanks to @roonyh for the help! ;)

**Comment by jigyasa-grover** [comment]
@YagoGG Resolve merge conflicts.

**Comment by YagoGG** [comment]
@jig08 Done!

**Comment by jigyasa-grover** [comment]
Awesome @YagoGG .
With this your [task](https://codein.withgoogle.com/dashboard/task-instances/5718735440576512/?sp-page=1) also gets completed.

**Comment by YagoGG** [comment]
Thank you!

**Comment by mananwason** [comment]
@jig08 please see to it that the commits are squashed. There are 25 commits in this PR which have been merged with the codebase. Reverting wouldn't help as well. @YagoGG Please file PR's with squashed commits. All relevant work in the PR can be summarised into just one commit.

**Comment by YagoGG** [comment]
Excuse me @mananwason, I don't understand what you're trying to say. Could you please try to explain it with more detail?

**Comment by mananwason** [comment]
@YagoGG You should squash your commits into a single one whenever you file a Pull request. Please see this https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md for instructions on how to squash commits.

**Comment by YagoGG** [comment]
@mananwason, I agreed with @SaptakS, @roonyh and @jig08 in the previous messages to squash just the first two commits (ea46e4b and 64bf811), because they were related, but not the rest of them, because they were different actions (although with the same objective).  
However, any advice on how could I  do better for future PR's will be very appreciated ;)

**Comment by mananwason** [comment]
@YagoGG You haven't squashed the first two commits and there are some commits like fix code styling etc. which are committed twice. You should atleast squash them. It's not desirable having multiple commits with same name like fixed photostack, fix code styling etc. Plus there are merge branches as well. Also, imo all of these commits are for the same cause, i.e to improve the speed of the page, hence should be in a single commit.

**Comment by YagoGG** [comment]
@mananwason Just out of curiosity, why isn't desirable to have multiple commits as you mention?

**Comment by mananwason** [comment]
@YagoGG Long Answer : http://programmers.stackexchange.com/questions/263164/why-squash-git-commits-for-pull-requests

tl:dr : https://twitter.com/jamesfublo/status/402407321265274881 :wink:

**Comment by roonyh** [comment]
Direct route does not have to be a single commit though. Its very common to have multiple commits in a single pull request. Each commit is a separate step of the route.

**Comment by YagoGG** [comment]
Great references @mananwason.

Okay, now I see the point of squashing. Thank you both!

**Comment by mananwason** [comment]
@roonyh there is no hard and fast rule but I believe everything related to a single feature should come under one commit. It makes the history clean and if we need to revert/remove a feature we can easily just remove the particular commit. Plus in this PR there were many unnecessary commits as well like ones with same names, merge commits, some commits from other, so this PR should have been cleaned up anyways.

@YagoGG Thanks. I hope that you'll squash and push in the future now :smiley:

**Comment by roonyh** [comment]
@mananwason we can revert a whole PR just fine. Having separate commits make it even more fine tuned because we can revert just the commit that introduced the error while keeping others. There is no reason to make everything related to a single feature into a single commit! Its desirable to have everything related to a feature in a single PR. But not necessarily in a single commit.  

yes @YagoGG's rebase operation hasn't gone perfect.

**Comment by YagoGG** [comment]
> @YagoGG's rebase operation hasn't gone perfect.

Yeah, sorry about that :sweat_smile:

**Comment by roonyh** [comment]
No problem. Git is hard. Very hard. :)

**Pull request merged**
