### PR TITLE
own contribution

### PR DESCRIPTION
**Pull request by AvramPop**
made yacy roWiki page

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://AvramPop.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@AvramPop Resolve merge conflicts.

**Comment by AvramPop** [comment]
i do not see any merge conflict...

**Comment by jigyasa-grover** [comment]
@AvramPop A merge conflict occurs when two or more people change the same line(s) in that same file, or if one person decides to delete it while the other person decides to modify it.

In my opinion, this PR must be showing `merge conflicts` at your side as well.

To resolve them, you could refer [this](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md).

**Comment by AvramPop** [comment]
it doesent show anything :))) should i delete the repo and remake all the work?

**Comment by AvramPop** [comment]
http://s30.postimg.org/jnaxvjp8h/asdf.png

**Comment by jigyasa-grover** [comment]
@AvramPop It should show in the `Conversation` section ...

**Comment by AvramPop** [comment]
Nothing

**Comment by AvramPop** [comment]
can you send me a link?

**Comment by jigyasa-grover** [comment]
Of ?

**Comment by AvramPop** [comment]
or should close the pr and remake it? i will do that if i have to

**Comment by AvramPop** [comment]
of the conflict...or where i can fix it

**Comment by jigyasa-grover** [comment]
I did send the doc to refer.
Here is the link again https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md

**Comment by AvramPop** [comment]
all right. im gonna remake it

**Pull request closed without merging**
