### PR TITLE
Added bio viewing

### PR DESCRIPTION
**Pull request by Meta-Maxim**
Hover over a member to view their bio.
DEMO: http://maxborsch.github.io/gci15.fossasia.org/

### CODE REVIEW

**Comment by mariobehling** [comment]
Hi, merge conflicts. Please fix it. Thank you!

**Comment by Meta-Maxim** [comment]
@mariobehling Ok, also could you check my task: 
"Get geolocation from OpenStreetMap using Postal code"
task? A mentor asked for your opinion.

**Comment by Meta-Maxim** [comment]
@mariobehling Big problem... This commit:
https://github.com/fossasia/gci15.fossasia.org/commit/83264e00238cf467aa79699f96111068c22b7f13
Makes the social links show over the images, but that's where my commit added the bio's.

I don't want to sound biased towards my design / make someone else's work for nothing, but wouldn't it be better to have the links like they were before (below the images) and the bio's inside the image? Not sure what to do, please help.

**Comment by mariobehling** [comment]
Not sure, how to solve this issue. Is there a library to add blobs like in comics for the bio?

**Comment by Meta-Maxim** [comment]
@mariobehling Ok so, before I scrap this update and add blurbs, do you think it would be better to have the site like it is in this pull or like it is in the other one that you accepted before this? Because it would be easier to revert the other commit if you prefer this one over it, I'm ok with either way.

Also the other commit wasn't up to date, it got rid of mentors.

**Comment by mariobehling** [comment]
Please base your development on the current site as it is right now and add the blurbs. I am curious how it will look like.

**Pull request closed without merging**
