### PR TITLE
Fix #118

### LINKED ISSUE #118: Bad allign twitter, FB and YT on mobile phones in horizontal rotation
How do you think is this same issuse as #91 ? I am not sure, if yes I will close.
screenshot_2015-12-20-17-52-51
screenshot_2015-12-20-17-53-06
screenshot_2015-12-20-17-53-12

### PR DESCRIPTION
**Pull request by bartekjacak**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://xennon.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@xennon It doesn't seem to have fixed the issue.

12470816_814223835390827_382884346_o

**Comment by bartekjacak** [comment]
But the issue was only about horizontal rotation.

**Comment by jigyasa-grover** [comment]
Your fix changed it to this.

**Comment by bartekjacak** [comment]
Oh okey, I'll fix it as soon as I can.

**Comment by mananwason** [comment]
@xennon status?

**Comment by bartekjacak** [comment]
@mananwason It's too late, because this bug was fixed, I close this PR.

**Pull request closed without merging**
