### PR TITLE
Additya Popli

### PR DESCRIPTION
**Pull request by anukul**
GCI Task

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://anukul.github.io/gci15.fossasia.org

**Comment by anukul** [comment]
Tweet: https://twitter.com/additya1998/status/690505302857252864

**Comment by jig08** [comment]
Hey @anukul , Resolve merge conflicts. [This](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) might help.

**Comment by mananwason** [comment]
Hey @anukul are you working on this?

**Comment by jig08** [comment]
Closing this for now ...

**Pull request closed without merging**
