### PR TITLE
Added Flickr link and icon

### PR DESCRIPTION
**Pull request by shashank-sharma**
I tried to add one more link of flickr with icon at footer.
After updating it looks like : 

screenshot from 2015-12-27 18 41 59

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://shashank-sharma.github.io/gci15.fossasia.org

**Comment by jig08** [comment]
Awesome @shashank-sharma !

**Comment by roonyh** [comment]
@shashank-sharma @jig08 Wait, Isn't that the icon of Instagram though?

**Comment by jigyasa-grover** [comment]
@roonyh I was just opening an issue for the same :P

**Comment by roonyh** [comment]
Ah cool :-)

**Comment by jigyasa-grover** [comment]
Done. Issue #233

**Comment by shashank-sharma** [comment]
@roonyh @jig08  I was also having the same doubt but in your main site http://fossasia.org/ at footer there is that same logo which is of instagram which I totally agree but the link is of flickr.

**Comment by roonyh** [comment]
@shashank-sharma ah. fair enough :) Could you file an issue here? https://github.com/fossasia/fossasia.org/issues Thanks!

**Comment by jigyasa-grover** [comment]
@roonyh @shashank-sharma Here it is https://github.com/fossasia/fossasia.org/issues/1

**Comment by shashank-sharma** [comment]
@jig08 @roonyh  Will it be fine if I made a PR for that issue which is in fossasia ?

**Comment by mananwason** [comment]
@shashank-sharma Go ahead !!

**Comment by jigyasa-grover** [comment]
@shashank-sharma Sure  :)

**Pull request merged**
