### PR TITLE
GCI Task Done

### PR DESCRIPTION
**Pull request by Sharatsa**
Added My Picture And Creditials

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Sharatsa.github.io/gci15.fossasia.org

**Comment by shiftsayan** [comment]
- I guess your branch was not up to date with the origin. Few names are missing from the list on your branch.
- And your image was Sharat.png and you have mentioned Sharat.jpg in the .yml file.
- You need to mention the Facebook username i.e. the part after www.facebook.com/ . You have entered the complete URL as a result the hyperlink to you Facebook profile is not working.
- Also, you need to have a - before your name on the .yml file, so your data has overridden Sanjay Tharagesh's data (his Twitter link is shown with your name).

**Comment by samarsault** [comment]
Nice ! Please note that your image should be in a 1:1 ratio i.e. width = height to display it as a nice circle.
Also, please rebase your pull and squash your commits into one.

**Comment by abishekvashok** [comment]
@Sharatsa please solve the merge conflicts (They arise when you are not modifying the upto date file and another student has submitted a new commit to the file you are modifying) . Please also fix the image ratio and squash the commits using git rebase

**Comment by jigyasa-grover** [comment]
@Sharatsa Still working on this ? Let us know in case of any issues.
Regarding resolving merge conflicts, [this](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) might help.

**Pull request closed without merging**
