### PR TITLE
add project

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://nolik2000.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@nolik2000 It's not showing up in your gh-pages. Please check again

**Comment by ghost** [comment]
Could you say why? I don't understand what I did incorrect(

**Comment by ghost** [comment]
I find mistake yaeh!!!

**Comment by mananwason** [comment]
Cool. Fix it and then we can merge !!

**Comment by ghost** [comment]
I fixed it)

**Comment by mananwason** [comment]
@nolik2000 Could you please squash both the commits. Thanks!

**Comment by ghost** [comment]
OK

**Comment by mananwason** [comment]
You can refer to this https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md

**Pull request closed without merging**
