### PR TITLE
Fixed social media widgets and replaced twitter widget with loklak

### PR DESCRIPTION
**Pull request by codethejason**
Instead of using the twitter widget, the loklak API will be used instead of the Twitter iframe #296. I chose not to create a whole new section because there are already too many. I deleted the Twitter widget as this is replacing it.

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://codethejason.github.io/gci15.fossasia.org

**Comment by sudheesh001** [comment]
Great, Can you squash them into one single commit please. Here's how you can do this
https://asciinema.org/a/11269

**Comment by codethejason** [comment]
@sudheesh001 I understand how to squash commits, but I wanted three separate commits cause they are different things.

**Comment by codethejason** [comment]
@sudheesh001 I combined commits 1 and 2 as 1 was a small style change but I think 3 should stay by itself because it's a "checkpoint" just in case someone wants to revert it back.

**Comment by roonyh** [comment]
Looks good! thanks.

**Pull request merged**
