### PR TITLE
Re-add Student (Li Zhaoqi)

### PR DESCRIPTION
**Pull request by Eclipse-Dominator**
First ver is deleted due to too much bug in the file

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Eclipse-Dominator.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@Eclipse-Dominator Resolve merge conflicts. [This](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) might help.

**Comment by Eclipse-Dominator** [comment]
Resolved merge conflicts (f406453)

**Comment by samarsault** [comment]
Please squash your commits.

**Comment by mananwason** [comment]
@Eclipse-Dominator Please remove the merge remote commit as well

**Comment by Eclipse-Dominator** [comment]
I was unable to squash the 2 commits.

**Comment by SaptakS** [comment]
You can try this https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md to squash your commits. Also your PR includes merging other branches. Please remove such commits.

**Pull request closed without merging**
