### PR TITLE
Update the files

### PR DESCRIPTION
**Pull request by sudo-panda**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Baidya99.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@Baidya99 Please squash all commits into one. You can follow instructions [here](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md)

**Comment by jigyasa-grover** [comment]
@mananwason I think @Baidya99  is erroneously trying to push his task code directly into this repo.

**Comment by SaptakS** [comment]
I have already told him what to do in GCI task.. @Baidya99 I asked you to remove hangman.html and hangman.js from this repo...

**Comment by jigyasa-grover** [comment]
Cool @SaptakS !

**Comment by sudo-panda** [comment]
How can I squash all commits into one using github desktop?

**Comment by sudo-panda** [comment]
I have deleted the hangman.htm and hangman.js files. Can you now merge the two?

**Comment by jigyasa-grover** [comment]
- Build failing
- Commits not squashed

@Baidya99 Kindly look into these issues ?

**Pull request closed without merging**
