### PR TITLE
Fixed footer

### PR DESCRIPTION
**Pull request by PiotrKowalski**
https://github.com/fossasia/gci15.fossasia.org/issues/77  I've got small problems with squashing. It is why i've got so many commits

### CODE REVIEW

**Comment by codethejason** [comment]
Have you tried "git rebase -i HEAD~6"? It opens up an interactive window in which you can switch 'pick' to 'squash'.

**Comment by PiotrKowalski** [comment]
I tried by "git rebase id_commit". I will try with HEAD~6. Have I to close pull request and try it?

**Comment by codethejason** [comment]
You can modify your commits while keeping the PR open. What HEAD~6 does is go back 6 commits.

**Comment by samarsault** [comment]
Try 
`git reset --hard upstream/gh-pages`
Note that It will reset your fork to the fossasia/gci15.fossasia.org
And then re-commit your changes.

**Comment by seadog007** [comment]
@samarjeet27 well, --hard will reset all files.....

**Comment by samarsault** [comment]
@seadog007 Yeah, but locally. He can see the changes from this pull request and re-commit cleanly and push. Squashing the commits is a better option though.

**Pull request closed without merging**
