### PR TITLE
Fixed issue #377 as part of GCI

### PR DESCRIPTION
**Pull request by abishekvashok**
Fixed issue https://github.com/fossasia/gci15.fossasia.org/issues/377 as part of GCI also I added title too. Please check it out and accept the task

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by seadog007** [comment]
Maybe you can change your title

**Comment by abishekvashok** [comment]
No thanks

**Comment by abishekvashok** [comment]
Please accept/approve my task

**Comment by sudheesh001** [comment]
Please squash the commits into one single commit.

**Comment by roonyh** [comment]
The first project in the list is not aligned properly.
screen shot 2016-01-13 at 2 03 15 pm

**Comment by abishekvashok** [comment]
@roonyh it's ok now check out the code I have also squashed the commits together as directed by @sudheesh001 see the merged commit : https://github.com/Abhi2424shek/gci15.fossasia.org/commit/9262c6b7ba7335ab1b01e2cc28c5eab61fb9763a

**Comment by roonyh** [comment]
@Abhi2424shek It doesn't look like the rebase has gone correctly. If squashed into a single commit you shouldn't see more than a single commit here. https://github.com/fossasia/gci15.fossasia.org/pull/405/commits

The code and the functionality looks fine now. So please work with @sudheesh001 to get the commits in order then we can merge this.

**Comment by roonyh** [comment]
And see comments on #377

**Comment by abishekvashok** [comment]
So what should I do? Look you told to add section games and I added one! you wanna make it light weight? I may do it for the entire site but that will resolve another issue so please accept this and I have another way to speed up the site.

**Comment by abishekvashok** [comment]
And one more thing wasn't the rebase successful any help from you anything would be appreciated @roonyh  @sudheesh001

**Comment by abishekvashok** [comment]
See here, this is a single commit right - https://github.com/Abhi2424shek/gci15.fossasia.org/commit/9262c6b7ba7335ab1b01e2cc28c5eab61fb9763a

**Comment by abishekvashok** [comment]
Ok delete the rest commits except this one https://github.com/Abhi2424shek/gci15.fossasia.org/commit/9262c6b7ba7335ab1b01e2cc28c5eab61fb9763a . I merged them all into a single commit but they are all exisiting

**Pull request closed without merging**
