### PR TITLE
Solved issue to add a light weight section Games to 'FOSSASIA GCI 201…

### PR DESCRIPTION
**Pull request by abishekvashok**
…5 Website' as a part of Google Code-in 2015

Solved issue to add a light weight section Games to 'FOSSASIA GCI 2015
Website' as a part of Google Code-in 2015 . I also added arrows to the
photostack. So please take a quick review and accept it. It never takes much of page load speed because another photstack gallery is being loaded and only the content and the images that are mandatary to load in the games section are being loaded.

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by abishekvashok** [comment]
Please accept it before any conflicts arise @roonyh @prwatch @nikunjness @sudheesh001 @mariobehling and @roonyh  the arrows are here this time and are bug free ! 100% ! I HOPE YOU'D ACCEPT THIS FAST AS I HAVE TO MOVE TO THE REST OF TASKS , please help me on making my way into the grandfinals - yours faithfully Abishek V Ashok.

**Comment by abishekvashok** [comment]
@roonyh please be sure to accept my task

**Comment by abishekvashok** [comment]
I am now behind and thus have a large % of getting into a conflict so resolve it soon guys @roonyh @sudheesh001 @nikunjness @mariobehling @harshkothari410 @YashKumarVerma @leto

**Comment by roonyh** [comment]
I see that we have merged #436 which better addresses the requirements of #377 . And you are removing it. Lets keep it.

For this task could you please add the left right arrows only to the **Gallery**?

Don't worry about squashing commits if you find that difficult. Just add left right arrows only to **Gallery** and keep the Games section we have now. Don't remove it. Don't add a new one.

Then I'll close your task. 

Thanks!

**Comment by abishekvashok** [comment]
I minute sir please wait at-least a 10 minutes online I will post the new pull request's link here

**Comment by abishekvashok** [comment]
@roonyh please see : https://github.com/fossasia/gci15.fossasia.org/pull/450

**Comment by abishekvashok** [comment]
@roonyh I have done all that you have said, hope you'd accept it

**Pull request closed without merging**
