### PR TITLE
Moved the social bar to the extreme right

### PR DESCRIPTION
**Pull request by shiftsayan**
This makes the social bar more accessible, moves important information to the middle and doesn't interfere with the text flow!

### CODE REVIEW

**Comment by shiftsayan** [comment]
screen shot 2015-12-28 at 10 35 31 pm

**Comment by jigyasa-grover** [comment]
@shiftsayan I am not really sure about this move.

**Comment by shiftsayan** [comment]
In my opinion, good design philosophy dictates that text should be with text. Earlier the social bar was creating a barrier of sorts between the two textual pieces. Moreover, since the social buttons are where users will click, and the sides are comparitively easier to reach than the center, the accessibility is improved. Lastly, this brings the About FOSSASIA section in the middle of the footer, a place which it deserves. :)

**Comment by roonyh** [comment]
It is really subjective what a good design is and there are more explicit problems with this section. For example how it looks on medium displays.
screen shot 2015-12-28 at 10 44 15 pm

**Pull request merged**
