### PR TITLE
improve

### PR DESCRIPTION
**Pull request by ghost**
Improvement to social media section

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://nolik2000.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@nolik2000 Include a more descriptive title or add the details in the description box so that we know what exactly is the PR for :)

**Comment by mananwason** [comment]
@nolik2000 Please remove the changes here. Doesn't look nice. Content is getting cropped.
screen shot 2016-01-17 at 11 13 48 pm

**Comment by SaptakS** [comment]
I think the round effect doesnt look very good.. Also, squash the commits when you are done..

**Pull request closed without merging**
