### PR TITLE
fixed #529

### LINKED ISSUE #529: Make the lights out section more attractive
Hey guys the light's out section is'nt having that much standard as the rest of the page. The color also looks not that much great :) I hope someone will resolve this and the mentors would agree with this issue
untitled-2

### LINKED ISSUE #567: Improving/Reverting the changes done to *Lights Out* section
**Edit:** I believe some changes were made to the **Lights Out !** owing to Issue #529 which makes it stand out from others not in a good way. The heading and style doesn't gel with the other sections' formatting.

screenshot from 2016-01-21 23 33 42

---

**Prev:** I believe some changes were made to the **Lights Out !** owing to Issue #529 which makes it look tacky now. 

screenshot from 2016-01-21 23 23 28

### PR DESCRIPTION
**Pull request by jmurzaku**
Fixed #529 by changing font and size so it looks better. Also fixed #567

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://JamMurz.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@JamMurz Nice work. Is it possible to keep the heading format same as others and still have this effect of glow & dim ? Let us know otherwise.

**Comment by jmurzaku** [comment]
@jig08 ok I will fix work on this :)

**Comment by jmurzaku** [comment]
@jig08 I think it looks best the way I have it. I tried other fixes but the heading and font is the same as the rest of the website

**Comment by yasoob** [comment]
Hey @JamMurz You can do the following changes to make it look **much** better:
- [x] further reduce the `border-radius` of the header-title
- [x] Add some `margin-top` to the header-title
- [x] Change the font-family of the header-title to `Russo-one` to match all other titles
- [x] Reduce the font-size of the header-title to match all other header-titles

If you need any help then just comment here. I would be more than happy to assist you. Best of luck! :+1:

**Comment by jmurzaku** [comment]
@yasoob thanks I'll add those

**Comment by jigyasa-grover** [comment]
@yasoob Great suggestions ! @JamMurz See if incorporating 'em gives it a better look :)

**Pull request closed without merging**
