### PR TITLE
Added my picture in student images

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://rahulbisht12.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@rahulbisht12 Added your details in `_data/students.yml` ?

**Comment by ghost** [comment]
@jig08 yes maam. I have updated _data/students.yml

**Comment by jigyasa-grover** [comment]
@rahulbisht12 Squash your commits pls.
Refer https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md for help.

**Comment by ghost** [comment]
@jig08  I have Squash my commits please check.

**Comment by mananwason** [comment]
@rahulbisht12 you have included commits already  merged into the code base. There are merge conflicts. Please fix that.

**Comment by ghost** [comment]
@mananwason I am getting an error that Only those with write access to this repository can merge pull requests

**Comment by ghost** [comment]
@jig08 Please give me the write access :)

**Comment by jigyasa-grover** [comment]
@rahulbisht12 True, that only those with write access to this repository can merge pull requests. Hence you send a valid PR which we merge . Not everyone is provided with the write access to a repository.

**Comment by jigyasa-grover** [comment]
@rahulbisht12 Are you working on this ?

**Comment by mananwason** [comment]
@rahulbisht12 I am closing this for now.

**Pull request closed without merging**
