### PR TITLE
Gh pages

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://nolik2000.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@nolik2000 Seems like you made a new PR. The build passes but could you squash your commits ?
 [This](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) might help.

**Comment by prwatch** [comment]
DEMO: http://nolik2000.github.io/gci15.fossasia.org

**Comment by roonyh** [comment]
@nolik2000 I don't think you meant to do some of the changes here. Could you please reset everything and try again?

**Pull request closed without merging**
