### PR TITLE
Small fixes to lights out section

### PR DESCRIPTION
**Pull request by jmurzaku**
Added some small fixes to lights out section

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://JamMurz.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@JamMurz I think this makes the lights on and off button equal sized for mobile devices. Right?

**Comment by jmurzaku** [comment]
@mananwason I think i made them equal sized in my last pull request. In this one i fixed row issues with the avatars.

**Comment by jmurzaku** [comment]
@mananwason to make the button nicer and a bit more mobile friendly, could i use http://www.bootstrap-switch.org/?

**Comment by mananwason** [comment]
Oh I though it was the other way round with the fixes @JamMurz . Sure Go ahead with bootstrap switch. I think it would look much better :grinning:

**Pull request merged**
