### PR TITLE
Gh pages

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://nolik2000.github.io/gci15.fossasia.org

**Comment by prwatch** [comment]
DEMO: http://nolik2000.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@nolik2000 Please squash commits. You can refer to [this](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md).

**Comment by mananwason** [comment]
Please solve the merge conflicts also

**Pull request closed without merging**
