### PR TITLE
Added 300x300 image and credentials

### PR DESCRIPTION
**Pull request by oanarosca**
I hope everything's alright :)

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://oanarosca.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@oanarosca Why did you close this PR ?

**Comment by prwatch** [comment]
DEMO: http://oanarosca.github.io/gci15.fossasia.org

**Comment by oanarosca** [comment]
Uh oh, sorry :flushed:

**Comment by jigyasa-grover** [comment]
It can be merged perfectly @oanarosca :)

**Comment by jigyasa-grover** [comment]
No issues, see your name up and running at [gci15.fossasia.org](http://gci15.fossasia.org/#students) @oanarosca !

**Pull request merged**
