### PR TITLE
added Doris Lee credentials and photo

### PR DESCRIPTION
**Pull request by kngoledge**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://kngoledge.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@kngoledge please squash commits.

**Comment by jigyasa-grover** [comment]
Hey @kngoledge . How is it going ?

**Comment by kngoledge** [comment]
Hello, I didn't know how to squash commits so I followed this guide: https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/
Then I pushed all the changes from my local computer to my fork. Do I have to do another pull request? Did I do it wrongly?

**Comment by kngoledge** [comment]
Sorry, I'm still figuring things out. I think I know what happened. I followed the guide and was able to squash commits okay but I'm not sure how to transfer the changes from my local copy to the github repository. At first I typed in git commit and then git pull and then git push. Does this sound right?

**Comment by mananwason** [comment]
@kngoledge you can follow this guide from the repo as well.
https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md

**Comment by kngoledge** [comment]
Thank you! That was really helpful. Does it look okay now?

**Comment by mananwason** [comment]
@kngoledge The branch has merge conflicts. Please solve them. Cheers!

**Pull request closed without merging**
