### PR TITLE
The change I have made is to add me in the GCI 2015 students list as per the task.

### PR DESCRIPTION
**Pull request by arpitkamboj**
Added my info in students.yml and added my photo in the students
folder...

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://digitalripperynr.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@digitalripperynr Kindly resolve merge conflicts.

**Comment by arpitkamboj** [comment]
I am unable to understand what conflict is it showing.....Please help.

**Comment by arpitkamboj** [comment]
It is showing no new line at the end of the file.....What does that mean??
new

**Comment by jigyasa-grover** [comment]
@digitalripperynr 
_Resolving Merge Conflicts_ You'll need to update your branch with new commits from master, resolve those conflicts and push the updated/resolved branch to GitHub. 

Something like this:

**Step 1: From your project repository, check out a new branch and test the changes.**

```
git checkout -b digitalripperynr-gh-pages gh-pages
git pull https://github.com/digitalripperynr/gci15.fossasia.org.git gh-pages
```

**Step 2: Merge the changes and update on GitHub.**

```
git checkout gh-pages
git merge --no-ff digitalripperynr-gh-pages
git push origin gh-pages
```

**Comment by jigyasa-grover** [comment]
@digitalripperynr `It is showing no new line at the end of the file.....What does that mean??` No issues, it simply means that there is no new line after the last. Doesn't seem to be a cause of worry.

**Comment by arpitkamboj** [comment]
I will do this all from beginning.. Sorry for inconvenience

**Comment by jigyasa-grover** [comment]
You could have simply rectified this PR, but as you feel comfortable.

**Comment by roonyh** [comment]
> Something like this:
> 
> Step 1: From your project repository, check out a new branch and test the changes.
> 
> git checkout -b digitalripperynr-gh-pages gh-pages
> git pull https://github.com/digitalripperynr/gci15.fossasia.org.git gh-pages
> Step 2: Merge the changes and update on GitHub.
> 
> git checkout gh-pages
> git merge --no-ff digitalripperynr-gh-pages
> git push origin gh-pages

@jig08 I am not sure if these instructions work from a fork of the repo. They are supposed to work from the main repo itself. Have you tested them from a fork?

Students who are first timers to git and Github are having trouble with this. Maybe we could have some instructions for them in https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md?

**Comment by arpitkamboj** [comment]
Yes sir
They are a bit different..

Please try to explain that well............

**Pull request closed without merging**
