### PR TITLE
Updated info

### PR DESCRIPTION
**Pull request by shreyassanghvi**

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
@shreyassanghvi Picture was added or not ?

**Comment by jigyasa-grover** [comment]
Oh, I see you have different PR for that #161 .

**Comment by shreyassanghvi** [comment]
@jig08 yes the picture was added as shreyas.jpg

**Comment by jigyasa-grover** [comment]
@shreyassanghvi This PR has merge conflicts. Kindly see to it :)

**Comment by shreyassanghvi** [comment]
@jig08 which one of the PR the image or the change in student.ml?

**Comment by jigyasa-grover** [comment]
Both are showing merge conflicts.

**Comment by shreyassanghvi** [comment]
what should i od... how to see if there is a conflict or not

**Comment by shreyassanghvi** [comment]
how do i know and solve the conflict 
this is my first time using Git

**Comment by jigyasa-grover** [comment]
@shreyassanghvi 

---

**`Checkout via command line`**

If you cannot merge a pull request automatically here, you have the option of checking it out via command line to resolve conflicts and perform a manual merge.

_HTTPS: https://github.com/shreyassanghvi/gci15.fossasia.org.git_

**Step 1: From your project repository, check out a new branch and test the changes.**

```
git checkout -b shreyassanghvi-patch-2 gh-pages
git pull https://github.com/shreyassanghvi/gci15.fossasia.org.git patch-2
```

**Step 2: Merge the changes and update on GitHub.**

```
git checkout gh-pages
git merge --no-ff shreyassanghvi-patch-2
git push origin gh-pages
```

---

**Comment by samarsault** [comment]
@shreyassanghvi why did you delete  Cho Yin Yong's blog url ?

**Comment by choyiny** [comment]
That's very mean haha

**Comment by shreyassanghvi** [comment]
i was trying to move down to edit and by mistake i selected it but then undo the move to restore it... I am new to GIT so it was getting tough for me to submit changes and in nervousness i might have deleted it by mistake. Sorry @samarjeet27

**Comment by jigyasa-grover** [comment]
@shreyassanghvi Merge Conflicts.

**Comment by shreyassanghvi** [comment]
i am trying to delete all the other Pr's that i made by mistake. I will fix the conflicts ASAP @jig08

**Comment by choyiny** [comment]
Hey,

What I do when I mess up is just delete my fork and fork again. I did it for several times in this repo and imo is the fastest and easiest way for beginners dealing with git. Hope that helps.

**Pull request closed without merging**
