### PR TITLE
Create sticker

### PR DESCRIPTION
**Pull request by nitin10s**
final2
final1

I made these two stickers for Privly

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
Hey @nitin10s 
Nice work :)
Add the stickers on the `Privly Stickers` section on [gci15.fossasia.org](http://gci15.fossasia.org/) and we are good to merge.

**Comment by nitin10s** [comment]
The first one of these was the one i submitted for my task I made the second one too but due to short span of time i couldn't finalise them properly.. So uploaded both of them as if they could help Fossasia.

I found the secction Privly Stickers but I couldn't find a way to add to that section on website

**Comment by jigyasa-grover** [comment]
Okay, So here is how you proceed..
1. Add the stickers in `img/privly`
2. Edit `index.html` and add your details in the section [here](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/index.html#L1189) following the format:

```
<div class="thumbnail folio-thumb">
    <figure class="gallery-item">
        <img alt="Sticker" src="img/privly/<your_sticker_name>.PNG" >
            <figcaption class="img-title">
                <h4><your header>
                    <a href="https://github.com/<your GitHub handle>">
                       <i id="github" class="icon-github">
                       </i>
                    </a>
                 </h4>
           </figcaption>
        </figure>
     <h3>Made by ....</h3>
 </div>
```

**Comment by abishekvashok** [comment]
@nitin10s still on this :)

**Comment by abishekvashok** [comment]
@jig08 status

**Comment by jigyasa-grover** [comment]
@Abhi2424shek so that we don't lose this precious work, can you add the stickers pls ?

**Comment by abishekvashok** [comment]
@jig08 sorry I just saw it would do it in just a bit of time, pls wait.

**Pull request closed without merging**
