### PR TITLE
Update students.yml

### PR DESCRIPTION
**Pull request by naveenbalachandran**
naveen

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
The photo is still not added in `img/students` ...

**Comment by naveenbalachandran** [comment]
Could you please add it yourself from pull request 468

**Comment by naveenbalachandran** [comment]
I cant seem to do it

**Comment by jigyasa-grover** [comment]
Well, you have claimed the corresponding GCI task @naveenbalachandran 

You could start afresh by: 
- Forking the repo
- Adding your photo in `img/students` 
- Making an entry of your name an details in `students.yml` 
- Sending a new Pull Request (PR) for the same :)

**Comment by naveenbalachandran** [comment]
I cant seem upload my picture it says i am not authorized to do it

**Comment by jigyasa-grover** [comment]
Closing this. A new PR #475 has been made in this regard.

**Pull request closed without merging**
