### PR TITLE
optimized images and also fixed images link

### PR DESCRIPTION
**Pull request by vicky002**
I optimized images and also fixed raheel's broken image link. 

@jig08  Please check once. 

Thanks.

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://vicky002.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
Nice work @vicky002. Merging!

**Comment by vicky002** [comment]
@mananwason  Hey, If you see the [DEMO](http://vicky002.github.io/gci15.fossasia.org) link 
the image of Raheel Saghir is still broken in the students. We just need to change the name of the image from Raheel102 to raheel102. 

I changed the name in my local repo but thing is changing the file name is not considered as the change by GitHub. That's the reason image is still broken. :crying_cat_face: .

**Comment by mananwason** [comment]
@vicky002 You can delete the git cache and then add everything again. This will probably solve the issue. Create a new PR after fixing it. Thanks!

**Pull request merged**
