### PR TITLE
Saved Page load speed. Resolved task #121

### PR DESCRIPTION
**Pull request by abishekvashok**
Hey mentors I did it saved a lot of data for the user by reducing the website size and also made it easy for others to develop. I minimized code and also put another uncompressed file which the students will modify and compress online or offline and override the compressed file. Please merge it soon as it modifies a lot of files thus increasing the chance for a conflict. @jig08 @mariobehling @roonyh

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by SaptakS** [comment]
screenshot from 2016-01-18 21 20 09
screenshot from 2016-01-18 21 20 48
 I guess the speed has gone down...
screenshot from 2016-01-18 21 27 39

**Comment by abishekvashok** [comment]
Hey common is 14 or 19 larger? @SaptakS you can see the chrome facts here at my task I uploaded the images, look you know I did optimized the files and how could the speed go down then? @SaptakS https://codein.withgoogle.com/dashboard/task-instances/5073449349283840/ and is that Ubuntu on your PC? :) The ratings were given by Google Chrome latest version so no worries as we all believe in Google right? And please take a stance before any conflicts arise as there is a large probability for conflicts as I have changed large number of files(Almost 46 files) I couldn't optimize a few images as they where already optimized. I know you'd understand the situation. Also disable cache and check it out. It's really saving a lot of data. Also it seems you hate sounds and you are having low power on your battery and less free storage on your laptop. :) !

**Comment by SaptakS** [comment]
Firstly 14 is less than 19 ... So when you score less its bad.. and in this case you scored less... I hope you get that.. Secondly, the images I posted are from google page insights which is also a service by google.. So believing in them isn't quite bad according to your own words.. Thirdly the page load time shown in your browser can depend on your internet speed at that time and varies accordingly.. So isn't at all a reliable way of checking optimization... And even then I am not telling that its not optimized.. I am just asking for others opinion... If others feel its optimized I am good to go.. Its just my opinion... Thanks.. :)

**Comment by abishekvashok** [comment]
I got it sir really sorry got another fix Ok sir any more suggestions @SaptakS and I never meant it that way

**Comment by abishekvashok** [comment]
Can I have my dinner please wait till then I got the images optimizing ok! @SaptakS with another optimizer

**Comment by abishekvashok** [comment]
any guess on how to enable compression @SaptakS

**Comment by abishekvashok** [comment]
Hey why isn't GitHub desktop finishing sync

**Comment by roonyh** [comment]
@Abhi2424shek GitHub desktop is for people starting to work on git. Its good as an starting point but more advanced uses of `git` requires git for command line. Its more fun too. You can do things like squashig commits from `git` command line. So try it :)

About the PR. Its hard to manage a huge PR like this easily with a lot of activity going on in the repo. So lets do it in small parts. You can start by reducing the size of images. Now that we show more people in a row image size could be smaller i guess.

We will move onto js on a different PR.

About JS compression: Running compressors manually is just a pain! Its great if you can provide a build option, a script to run by other students. that will minify everything. There are tools that work with jekyll. See how to build the site locally with jekyll. See: https://help.github.com/articles/using-jekyll-with-pages/

You will understand what goes on inside github pages servers.

**Comment by SaptakS** [comment]
@roonyh :+1:

**Comment by abishekvashok** [comment]
@roonyh ok I would compress and minimize the size of images first then accept that PR after which as said by you we will all together move on to javascript

**Comment by roonyh** [comment]
@Abhi2424shek Great!

**Pull request closed without merging**
