### PR TITLE
photo and details are added

### PR DESCRIPTION
**Pull request by ghost**
photo and information are added

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://zsanjay.github.io/gci15.fossasia.org

**Comment by ghost** [comment]
i have added my photo and other details

**Comment by prwatch** [comment]
DEMO: http://zsanjay.github.io/gci15.fossasia.org

**Comment by ghost** [comment]
actually i have included my photo and details but in the pull request , in the file changed , it shows some other changes which i have not done

**Comment by ghost** [comment]
actually i have included my photo and details but in the pull request , in the file changed , it shows some other changes which i have not done

**Comment by prwatch** [comment]
DEMO: http://zsanjay.github.io/gci15.fossasia.org

**Comment by ghost** [comment]
in the demo there is no photo of me

**Comment by ghost** [comment]
my photo is sanjay.jpg, name:sanjay tharagesh

**Comment by jigyasa-grover** [comment]
Hey @ghost , It shows no files changed...

**Pull request closed without merging**
