### PR TITLE
remove excess spaces and make picture show up

### PR DESCRIPTION
**Pull request by choyiny**
I believe this will fix issue with pull #119

### CODE REVIEW

**Comment by seadog007** [comment]
Why don't you test first?
you can use http://hkminegod.github.io/gci15.fossasia.org to see your change

**Comment by seadog007** [comment]
well, I don't know why your github page doesn't work :P

**Comment by hvardhanx** [comment]
Yep, test your changes first before making a pull request and please resolve merge conflicts.

**Comment by seadog007** [comment]
@royalharsh You can close it, I already fixed it

**Comment by choyiny** [comment]
thanks @seadog007

**Pull request closed without merging**
