### PR TITLE
Added loklak section and a project and changed repo links

### PR DESCRIPTION
**Pull request by codethejason**
Adds a rudimentary loklak section to display the active peers #295. For now it updates on page load but further improvements can be made. Third commit adds another project. Fourth commit changes all the github pages links to repository links.

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://codethejason.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@codethejason Squash your Loklak Peers commits.

**Comment by codethejason** [comment]
@jig08 Done.

**Comment by roonyh** [comment]
Project links going to the application itself is far more nicer!! What fun are the repositories?

**Comment by codethejason** [comment]
@roonyh A GCI task wanted only the repository links and then each repository should have a clickable demo link to the "meat" of the app. (https://codein.withgoogle.com/tasks/5444440197955584/). But I agree with you that the project link may look better.

**Comment by roonyh** [comment]
@codethejason Ah. Understood.

**Comment by Yathannsh** [comment]
@codethejason , just curious about the project you added. 
Your tasks requires you to add 'your own project' , whilst you have added a project by me. 
Though I have no problem just that,  I was about to make a PR and saw yours xD

**Comment by codethejason** [comment]
@Yathannsh Sorry that I didn't tell you beforehand: others were adding my projects so I thought everyone should just add projects as they appear. I have added mine in a different PR.

**Comment by Yathannsh** [comment]
@codethejason , not an issue! :+1:

**Comment by jigyasa-grover** [comment]
@codethejason Resolve merge conflicts.

**Comment by codethejason** [comment]
@jig08 Fixed conflicts.

**Comment by jig08** [comment]
@codethejason Cool. Merged !

**Comment by codethejason** [comment]
@jig08 For some reason the index.html didn't save. I will make another PR to fix the lines around 408.

**Pull request merged**
