### PR TITLE
Improved Blog Posts section dramatically

### PR DESCRIPTION
**Pull request by codethejason**
References PR #532 in that the section now displays the content of the blog posts and the link to the post.

scrn  

Further improvements can later be made to manage the blog post data more efficiently.

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://codethejason.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@codethejason please resolve conflicts

**Comment by mariobehling** [comment]
Hi, looks good. Could you make a few improvements, please:
- [x] Move section _Blog Posts_ just after _Students_ and sort menu items in top menu accordingly
- [x] Get rid of the _click to view blog posts_ and show blog post gallery without the click
- [x] expand blog article, so user can read it without scrolling
- [x] keep the list of blog articles below expanded article
- [x] keep all former six articles in the post and add 5 more articles
- [x] avoid depending on too many external tools on the site e.g. http://www.html-cleaner.com, http://www.textfixer.com/tools/remove-line-breaks.php (If we depend on a lot of external services, the site might not work if these services are offline or go out of service. I think it is often possible to achieve the same result in other ways. Could you check, please?)

**Comment by codethejason** [comment]
I will fix this shortly.

**Comment by codethejason** [comment]
@mariobehling I have added the enhancements. I have looked into a solution without those sites, but it is largely impractical because all formatting will be lost when pasting into a code editor. Furthermore, there are a bunch of tools online to perform the same thing as these two sites.

**Comment by codethejason** [comment]
@roonyh @mananwason Ready to merge.

**Comment by mananwason** [comment]
@codethejason I am not able to see any blog posts. Please check once. Cheers!
screen shot 2016-01-23 at 10 17 58 pm

**Comment by codethejason** [comment]
@mananwason After refreshing, you should be able to see it:  

scrn  

I didn't make any changes to hide the blog section.

**Comment by mananwason** [comment]
@codethejason No not working. Emptied caches as well. Doesn't work. Please check once.

**Comment by codethejason** [comment]
@mananwason It's working now after I made another change to load the script after document has loaded.

**Comment by roonyh** [comment]
@mananwason is it working now? Works for me at the moment.

**Comment by roonyh** [comment]
Not sure if having all blog posts in the same file is the right thing though. Many people will add to the end of the same file and we are looking at many merge conflicts. Just like the students.yml file. And it'll grow huge too. But we are at the end of the contest. So it won't be much of a problem.

**Comment by mananwason** [comment]
Looks good @codethejason !! We can merge! Cheers!

**Comment by mananwason** [comment]
@roonyh yes it works for me. What can be a better solution then according to you?

**Comment by roonyh** [comment]
Separate files for separate blog posts. And we load the file only if user clicks on it. The image is shown for all posts. If that works?

But no need to worry about that right now. Its good that this is merged sooner.

And for students.yml file we should add students in alphabetical order next year. should avoid a lot of merge conflicts we had this year.

**Pull request merged**
