### PR TITLE
Optimized Dynamic Img Load

### PR DESCRIPTION
**Pull request by Meta-Maxim**
Images now preload further out of view depending on your scroll direction.
No longer running $selector every frame.
Now uses quick array parsing instead of jquery stuff.
Stops checking after all images are loaded.

DEMO: maxborsch.github.io/gci15.fossasia.org

### CODE REVIEW

**Comment by codethejason** [comment]
You should get rid of the `Merge remote-tracking branch 'fossasia/gh-pages' into gh-pages` commits.

**Comment by Meta-Maxim** [comment]
@codethejason Yes I should. Although it would make no difference so not really. They don't show in the history since they have no changed files.

**Comment by codethejason** [comment]
If we're talking about formality here, I think our commits should be as clean as possible.

For example, in the commit history, the merges to the contributors' forks can clog the commit history.  
clog

clog

**Comment by Meta-Maxim** [comment]
@codethejason Yes I understand why you wanted me to squash them, I'm pretty sure I'm the one who told you to squash yours when you first joined. I'm just saying that it doesn't help very much because none of the mentors seem to be checking for this when they merge, and because of this all of the new members will still "clog" up the history. I'll squash once I add another commit in a few minutes.

**Comment by mananwason** [comment]
@MaxBorsch @codethejason is right. Please get rid of the merge commit and squash all the commits.

**Comment by Meta-Maxim** [comment]
@mananwason Done.

**Comment by mananwason** [comment]
@MaxBorsch Please resolve the conflicts as well

**Comment by Meta-Maxim** [comment]
@mananwason Fixed.

**Comment by mananwason** [comment]
Cool @MaxBorsch. Merging it.

**Pull request merged**
