### PR TITLE
Moved light project

### PR DESCRIPTION
**Pull request by antoniomdk**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://antoniomdk.github.io/gci15.fossasia.org

**Comment by antoniomdk** [comment]
I need to add the quiz game. Sorry

**Comment by jigyasa-grover** [comment]
@antoniomdk Squash commits , refer [this](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md)  for help. And kindly elaborate what is the PR for, I didn't quite get it.

**Comment by antoniomdk** [comment]
I can not rebase commits, the program says that it is already updated.

**Comment by jigyasa-grover** [comment]
Maybe you could start afresh by taking a clean fork ? Let know in case of any issues.

**Comment by antoniomdk** [comment]
How Can I take a clean fork? Deleting my existing one, and fork again?

**Comment by jigyasa-grover** [comment]
Yes @antoniomdk .

**Comment by antoniomdk** [comment]
But, I can miss my work or not?
Sorry for ask many question :)

**Comment by jigyasa-grover** [comment]
Yes, the new (clean) fork will have the latest code but without your changes as they weren't merged.

No issues, here to help :)

**Comment by jigyasa-grover** [comment]
@antoniomdk Updates pls ? Any help required ?

**Comment by antoniomdk** [comment]
No, sorry, I am finishing a task. When I have got it, I upload everything. Is it ok?

**Comment by jigyasa-grover** [comment]
Okay, so I am closing this for the time being...

**Pull request closed without merging**
