### PR TITLE
Fixed indentation in mentors.yml

### PR DESCRIPTION
**Pull request by jigyasa-grover**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://jig08.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@jig08 your gh-page is not working.

**Comment by jigyasa-grover** [comment]
@mananwason I wonder why, though the settings say it is published.
screenshot from 2016-01-09 14 34 31

**Comment by mananwason** [comment]
@jig08 Strange. Now it is working!!

**Comment by jigyasa-grover** [comment]
@mananwason Indeed.

**Comment by jigyasa-grover** [comment]
@mananwason 

```
From: GitHub <support@github.com>
Date: Sat, Jan 9, 2016 at 2:31 PM
Subject: [jig08/gci15.fossasia.org] Page build warning
To: Jigyasa Grover <grover.jigyasa1@gmail.com>


The page build completed successfully, but returned the following warning:

CNAME already taken: gci15.fossasia.org. Check out https://help.github.com/articles/my-custom-domain-isn-t-working/#cname-already-taken for more information.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

If you have any questions you can contact us by replying to this email.

```

**Comment by mananwason** [comment]
Oh. I know why this is happening. You have tried to setup a CNAME record in your repo which doesn't work.

**Comment by jigyasa-grover** [comment]
Well, the repo was simply forked and no additional CNAME record was setup.

**Pull request merged**
