### PR TITLE
Added blogs section

### PR DESCRIPTION
**Pull request by abishekvashok**
Added section blogs as a part of GCI in a user friendly manner with minimal code(no js[except to load content] only css). Also emphasised to save page load time. @jig08 @roonyh @sudheesh001 @SaptakS @niccokunzmann . Please review and accept(if possible) before any conflicts arrise. Here's the link to my task: https://codein.withgoogle.com/dashboard/task-instances/6251847782236160/?sp-page=1

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@Abhi2424shek still not working. Please check!

**Comment by abishekvashok** [comment]
Done @mananwason here's the new commit

**Comment by mananwason** [comment]
Sorry @Abhi2424shek Still not working!! Please take some time and figure out the issue.

**Comment by mananwason** [comment]
@Abhi2424shek It works when I click on View blog button but it doesn't work if I click anywhere else on the figure. Otherwise nice work :smile:

**Comment by abishekvashok** [comment]
Fixed it! now see it  ok

**Comment by mananwason** [comment]
Please check again @Abhi2424shek. Not working!!

**Comment by abishekvashok** [comment]
@mananwason delete cache and try and sorry for newer request but that's all I can do :( here's it with fixed link: https://github.com/fossasia/gci15.fossasia.org/pull/532

**Pull request closed without merging**
