### PR TITLE
Add 5 more blog posts

### PR DESCRIPTION
**Pull request by YagoGG**
This PR includes the following blog posts:

[**Fossasia - Codein Organiser**](http://codein-dwij.github.io/blog_hugo/post/fossasia/), by Dwij Jha (@codein-dwij)
[**What Open Source Is For Me**](http://juanvulcano.github.io/post/What-open-source-is-for-me/), by Juan F. Verhook (@juanvulcano)
[**How to setup a blog using Hugo**](https://poprosturonin.github.io/post/setupHugo/), by Bartosz Wiśniewski (@poprosturonin)
[**My Google Code-in Experience with FOSSASIA**](http://codethejason.github.io/blog/gciexperience/), by Jason Wong (@codethejason)
[**Google Code-in 2015/16**](http://yagogg.github.io/blog/google-code-in-2015/16/), by Yago González (@YagoGG)

And also uses a loseless compression in all the thumbnails, for improved loading speed.

Thank you guys for these great posts!

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://YagoGG.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@YagoGG Please squash commits. Then we can merge. Thanks!

**Comment by mananwason** [comment]
Plus there are merge conflicts as well. Please resolve them as well. Cheers!

**Comment by YagoGG** [comment]
Yup, I just realised after doing the PR, sorry about that. Fixing them!

**Comment by codethejason** [comment]
@YagoGG I have already added my experience post in my PR.

**Comment by YagoGG** [comment]
@codethejason Ooops! Fine, I'll replace it for another one. Thanks for the heads-up ;)

**Comment by mananwason** [comment]
Very well @YagoGG. Please solve the conflicts as well. Thanks!

**Comment by YagoGG** [comment]
@codethejason's post has been replaced by Sayan Chaudhry's (@shiftsayan) [**Starting with Jekyll**](http://sayanchaudhry.me/blog/jekyll/2015/12/29/getting-started-with-jekyll.markdown.html)

Merge conflicts solving on the way

**Comment by mananwason** [comment]
Awesome :+1:

**Comment by codethejason** [comment]
@YagoGG Try to merge it without the `Merge branch 'gh-pages' of https://github.com/YagoGG/gci15.fossasia.org… …
… into gh-pages` commit by using the `git pull --rebase` command so the commit history is cleaner.

**Comment by YagoGG** [comment]
I actually got over the merging, but I'm unable to squash the last 3 commits into one, when I `git rebase -i HEAD~3`, the last three commits that appear are:

```
07ac04c Added 3 of my projects to GCI website
44cd647 Add 5 more blog posts
8b246cf Add 5 more blog posts
```

Everything is pulled and up-to-date

Do you know why could this be?

**Comment by mananwason** [comment]
@YagoGG Which ones are yours?

**Comment by YagoGG** [comment]
@mananwason The two last

**Comment by mananwason** [comment]
@YagoGG Try `git pull --rebase` once and tell me the output of `git log`

**Comment by YagoGG** [comment]
@mananwason Okay, fixing the conflicts again :sweat:

**Comment by mananwason** [comment]
:+1:

**Comment by mananwason** [comment]
@YagoGG If you're not able to fix this, reset your fork and add the commits again.

**Comment by YagoGG** [comment]
@mananwason Yeah, I finally had to do that :/
Here's the link to my new PR: https://github.com/fossasia/gci15.fossasia.org/pull/621

Sorry about the inconvenience.

**Comment by mananwason** [comment]
No issues @YagoGG :smile:

**Pull request closed without merging**
