### PR TITLE
Re pullrequest for Task of Php webserver GCI

### PR DESCRIPTION
**Pull request by nicholascheow**
Add screenshot and adding it to gallery

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://nicholascheow.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
Great @nicholascheow !! Looks good :smile:

**Comment by nicholascheow** [comment]
Thanks alot for your assistance and patience. Ive learnt alot!

**Comment by mananwason** [comment]
Great. Glad I could help :grinning:

**Pull request merged**
