### PR TITLE
Minified a bunch of code

### PR DESCRIPTION
**Pull request by jmurzaku**
minified code for #700

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://JamMurz.github.io/gci15.fossasia.org

**Comment by abishekvashok** [comment]
Great but see this screenshots. This is the insight if your PR is merged. [http://JamMurz.github.io/gci15.fossasia.org]

image
image

And the current one.
[http://gci15.fossasia.org]
image
image

See the status[these are from page insights by Google], the rating has gone down. We need more rating. I am never saying you are not minifying it or anything, just letting you know. So it would be better to try to minify the images. I had great success on doing that. Also I had losses on trying the optimize the code.

However, @JamMurz this PR as to the file changes just changes the places of the code! What does that mean! I am not discouriging you here. I am know you can, just letting you know you should change your approach.

Try optimizing the images. :)

Speacial note for you ; "Google is providing the optimized images,js and css for the gci15.fossasia.org website", so why don't you try those to minify code and improve the speed
- Happy Coding @JamMurz

**Comment by roonyh** [comment]
@Abhi2424shek gci15.fossasia.org is served through Cloudflare, which helps the speed. So this is not a fair comparison.

**Comment by abishekvashok** [comment]
So @roonyh what other ways do you want it. Google page insights provide the valid data, they also get the data via cloudfare. They rate the speed and give us ways on how to achieve improvements :) I think that most other mentors are depending on that that's why I asked him to do so. Hope you get it @roonyh. :smiley: , the speed has decreased. Update: Hey I got a solution which you may want to work on guys. Go to page insights there you coud download the compressed code. Go and do it, would'nt that be great @roonyh . I know you all are seeing me as a shouting guy :gun: and you don't like me right? But as in a community you have to adjust right? :1234:

**Comment by roonyh** [comment]
@Abhi2424shek I know how Google page insights work and that it also gets the data via Cloudflare. That is the problem. gci.fossasia.org loads faster than JamMurz.github.io/gci15.fossasia.org anyway because its served through Cloudflare. Cloudflare does bunch of stuff to make the site load faster. So its not accurate to make any decisions based on comparing the page speed of the two.

And quite the contrary! I find you so enthusiastic and eager to help others. Which is great. People who work on open source are often busy people. So they just flat out say what they want to say. Don't assume that its because they don't like you :)

Its something you should and would eventually learn. To keep communication short and to the point.

**Comment by jmurzaku** [comment]
@Abhi2424shek thanks for the tips :)

**Comment by yasoob** [comment]
Hey @JamMurz You should not close this PR as I am pretty sure that these changes which you did would definitely increase the final speed of the website :)

**Comment by abishekvashok** [comment]
@yasoob he did great job, but remember to take a look at the commited changes! :)

**Comment by yasoob** [comment]
@Abhi2424shek what is the issue with the PR in your opinion? (Apart from the so-called speed reduction).

**Comment by abishekvashok** [comment]
@yasoob that's all! I never said anything like this PR has an issue, **please don't misunderstand** @yasoob. I just mentioned that the speed has gone down in page insights which means that it must be almost equal when served via cloudfare. As that is the case, improvements may be great and that's what I informed @JamMurz and he got what I meant. So please understand, got it :) :smiley:

**Pull request closed without merging**
