### PR TITLE
Added Distance-Finder in gallery

### PR DESCRIPTION
**Pull request by 9at8**
GCI 2015 - Task: World Distance Calculator

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://9at8.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@9at8 Resolve merge conflicts. [This](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) might help.

**Comment by 9at8** [comment]
@jig08 A little help please?
Do I have to do this?
<code>git pull --rebase upstream/gh-pages</code>
And then again generate a pull request?

**Comment by 9at8** [comment]
@jig08 is that all?

**Pull request merged**
