### PR TITLE
Added Hangman project to student games

### PR DESCRIPTION
**Pull request by sudo-panda**
I have included my project in the student section of the website.(L651-665)

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Baidya99.github.io/gci15.fossasia.org

**Comment by mariobehling** [comment]
Please update a description what you have changed.

**Comment by mananwason** [comment]
@mariobehling @Baidya99  I believe he has added his hangman project.

**Comment by sudo-panda** [comment]
Thankyou.

**Pull request merged**
