### PR TITLE
add student :Vic Chen

### PR DESCRIPTION
**Pull request by vicchen0502**
add student :Vic Chen

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://vicchen0502.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@vicchen0502 Please squash your commits and then we can merge :smile:

**Comment by vicchen0502** [comment]
@mananwason sorry for my poor english,but i really dont know what you mean 'squash my commit' 0_0"
can you explane it for me please?

**Comment by mananwason** [comment]
@vicchen0502 By squashing I mean that you should have only one commit in this pull request instead of 2. [This](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) might help you. Cheers!

**Comment by vicchen0502** [comment]
@mananwason I'm done.Do I need to do any thing alse?

**Pull request merged**
