### PR TITLE
Added newsletter resolved task. Closes issue #375

### PR DESCRIPTION
**Pull request by abishekvashok**
Added newsletter to official gci15 page of fossasia as a part of GCI

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by Abhi2424shek** [comment]
@jig08 @sudheesh001 @mariobehling take a look :)

**Comment by yasoob** [comment]
The social links have a lot of margin from top. Can you kindly reduce it? + Can you kindly add some margin between the footer text and the newsletter `div`?

**Comment by Abhi2424shek** [comment]
@yasoob man it's nice looking at it at this prespective and (don't be nervous with this question, I am not blaming you are you a mentor?, just a question not blaming you at any way)

**Comment by abishekvashok** [comment]
@yasoob :) remember I've willingly did'nt put the margin because the newsletter is for fossasia :)

**Comment by abishekvashok** [comment]
@kokoye2007  @mariobehling @roonyh @jig08 @harshkothari410 please be sure to accept[merge] the request before any conflicts arise I am gonna sleep! :) and link to task is : https://codein.withgoogle.com/dashboard/task-instances/4664245534851072/?sp-page=1

**Comment by jigyasa-grover** [comment]
@yasoob +1. The top margin for the social links could be reduced..

**Pull request closed without merging**
