### PR TITLE
Added geolocation projects section

### PR DESCRIPTION
**Pull request by yasoob**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://yasoob.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@yasoob Why exactly is this needed?

**Comment by yasoob** [comment]
@mananwason there is a [task](https://codein.withgoogle.com/dashboard/task-instances/6438646211149824/) related to it. I wasn't sure as well why this is needed.

**Comment by mananwason** [comment]
@yasoob It says that you need to move all geolocation tasks from Gallery to a new section. I believe that you haven't moved them from Gallery instead you have created them again. Please fix it. Thanks!

**Comment by yasoob** [comment]
I didn't remove the projects from the original gallery at first because there is this other section called "Student games" which also just copies the game projects from the main gallery and makes a new gallery out of it. It also doesn't remove the projects from the original gallery. I thought that this is how we are supposed to do this task.  

Nevertheless, I have updated the pull request :smile:

**Comment by mananwason** [comment]
Awesome!! Please follow instructions given in the task description. They are the evaluation points for us.

**Comment by yasoob** [comment]
I am sorry. It won't happen again (hopefully) :+1:

**Pull request merged**
