### PR TITLE
Added mentors info. and fixed #34

### LINKED ISSUE #34: The links and profiles style
The link style of student part is different with mentor part.

Mentor part: https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/index.html#L130-L144
Student part: https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/index.html#L169-L183

### PR DESCRIPTION
**Pull request by seadog007**
Fixed #34 and added informations of 8 mentors.

### CODE REVIEW

**Comment by seadog007** [comment]
http://seadog007.github.io/gci15.fossasia.org/

**Comment by seadog007** [comment]
There is the demo site:
http://seadog007.github.io/gci15.fossasia.org/

**Comment by mariobehling** [comment]
Hi, merge conflicts. Please fix it. Thank you!

**Comment by seadog007** [comment]
@mariobehling solved!

**Pull request merged**
