### PR TITLE
Added Antonio Molner data.

### PR DESCRIPTION
**Pull request by antoniomdk**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://antoniomdk.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
Hey @antoniomdk , Move your `Lights Out` project from `Gallery` to the corresponding `Lights Out` section ?

**Comment by antoniomdk** [comment]
Sorry, Where I can find that section?

**Comment by yasoob** [comment]
@antoniomdk  It is in the [index.html](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/index.html#L704) file.

**Pull request merged**
