### PR TITLE
Added French and extended animation

### PR DESCRIPTION
**Pull request by Abuissink**
I've added the French translation "Merci pour ton contribution" and extended the @keyframes move to accommodate the newer translations.

### CODE REVIEW

**Comment by sudheesh001** [comment]
@Abuissink Wouldn't using `votre contribution` be better than `ton contribution` ?
How about `Nous vous remercions de votre contribution` ?

I am not a french expert or something but I am just making a guess here from what I know.

**Comment by Abuissink** [comment]
True, I suppose it's good to be as formal as possible. Is there any way to update the pull request without having to make a whole new pull request? EDIT: Nvm, made a new commit. @sudheesh001 do you want me to squash them first or just keep this pull request with the two commits?

**Comment by sudheesh001** [comment]
@Abuissink Could you squash them up ? :smile:

**Comment by Abuissink** [comment]
About squashing, I figured out how to squash local commits using git rebase -i HEAD~n but I'm not sure how to tell origin that the commit history has changed, when I rebase and push git gives me an error about fast-forwarding. Ever since I've just been downloading the repo as a .zip, deleting the repo, re-cloning, extracting the repo zip into the new folder and commiting and pushing that to the new repo. Do you know how to get the origin to realise and accept that the commit history has changed?

**Comment by sudheesh001** [comment]
@Abuissink I just noticed your email and replied to it. I hope the instructions there are clear and have responded to your query.

**Pull request merged**
