### PR TITLE
Contributions by Yash

### PR DESCRIPTION
**Pull request by YashKumarVerma**
-Added Myself
-improved loklak table
-added animations
-fixed footer links

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://YashKumarVerma.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@YashKumarVerma Please remove your Geolocation project from the Gallery. Thanks!

**Comment by YashKumarVerma** [comment]
sir,
if i would remove my project, then there would be 2 commits and then I would need to squash commits.
Squashing commits is a thing which I can not do. To avoid squashing, I again and again delete the repo, fork it and then clone it.

**Comment by YashKumarVerma** [comment]
can i delete the geolocation project after it merges ?

**Comment by mananwason** [comment]
@YashKumarVerma I can guide you through squashing. You would need to remove this project, only then we can merge. Let me know which OS you're using.

**Comment by YashKumarVerma** [comment]
microsoft windows

**Comment by YashKumarVerma** [comment]
i have git installed
and desktop client too

**Comment by mananwason** [comment]
Go through [this](https://www.youtube.com/watch?v=msuJGG2iWjs) tutorial if you prefer videos or [this](https://mlichtenberg.wordpress.com/2014/11/12/using-git-rebase-to-combine-commits-github-for-windows/) if you prefer reading. Let me know if you have any doubts.

**Comment by YashKumarVerma** [comment]
thanks sir

**Comment by mananwason** [comment]
Sure :smiley:

**Comment by YashKumarVerma** [comment]
just a question, why there isn't a squash feature for desktop client ?

**Comment by YashKumarVerma** [comment]
I am following the text,
- do i have to open cmd or powershell ?
- do i have to remove from the geolocation section ?

**Comment by mananwason** [comment]
@YashKumarVerma Desktop client is just to get you started. Plus it doesn't give you most of the flexibility or features that the command lines does. 
You can open whichever. Both shall work but please see to it that you have git in your Path Environment variable.

**Comment by YashKumarVerma** [comment]
i have made the change in index.html. Now shall i make a commit using github desktop ?

**Comment by mananwason** [comment]
No I would urge you to use the command line. It's awesome.

**Comment by YashKumarVerma** [comment]
so the $ git add command ?

**Comment by mananwason** [comment]
Yes but I believe that you've already commited, right?

**Comment by YashKumarVerma** [comment]
no. Till now I have made only one commit. Now I have changed the index.html and am making a new commit for it

**Comment by mananwason** [comment]
Ok you can do 
`git add .`,
 then `git commit -m "<Commit message>"`,
 then `git rebase -i HEAD~2` If you need to squash 2 commits into one.

**Comment by YashKumarVerma** [comment]
what to do next sir ?

**Comment by mananwason** [comment]
Press esc and then type `:wq`

**Comment by YashKumarVerma** [comment]
pressing esc is doing nothing

**Comment by mananwason** [comment]
Did you type `:wq` ? Did that do anything?

**Comment by YashKumarVerma** [comment]
yes. It opened

**Comment by mananwason** [comment]
Okay so Now comment all lines you don't want for the commit message by adding a `#` against them. You need to have a single line as a commit message here. You can also just comment everything and then write a new message in a single line.

**Comment by YashKumarVerma** [comment]
is it correct ?

**Comment by mananwason** [comment]
Please make the message descriptive. It can be a bit long. Ideally you should write something like `added xyz, improved abc, added animations to xyz.....`

**Comment by YashKumarVerma** [comment]
sir, after adding message what to do ?

**Comment by mananwason** [comment]
Again `:wq`

**Comment by YashKumarVerma** [comment]
Is everything correct ?

**Comment by mananwason** [comment]
Yeah now you can do `git push -f <forkname> gh-pages` , where you can get forkname by doing `git remote -v` and seeing which remote is mapped to the URL of your fork.

**Comment by YashKumarVerma** [comment]
`git remove -v` gave this
fossasia        https://github.com/fossasia/gci15.fossasia.org.git (fetch)
fossasia        https://github.com/fossasia/gci15.fossasia.org.git (push)
origin  https://github.com/YashKumarVerma/gci15.fossasia.org.git (fetch)
origin  https://github.com/YashKumarVerma/gci15.fossasia.org.git (push)

**Comment by mananwason** [comment]
yeah so you can do `git push -f origin gh-pages` as origin refers to your fork.

**Comment by YashKumarVerma** [comment]
`
C:\xampp\htdocs\gci_task_example\gci15.fossasia.org>git push -f origin gh-pages
Username for 'https://github.com': YashKumarVerma
Password for 'https://YashKumarVerma@github.com':
Counting objects: 16, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (16/16), done.
Writing objects: 100% (16/16), 107.59 KiB | 0 bytes/s, done.
Total 16 (delta 9), reused 0 (delta 0)
To https://github.com/YashKumarVerma/gci15.fossasia.org.git
- f242d6b...ab40220 gh-pages -> gh-pages (forced update)
  `

**Comment by YashKumarVerma** [comment]
is it complete ?

**Comment by mananwason** [comment]
Can you send a screenshot?

**Comment by YashKumarVerma** [comment]
#### Also is the new pull request section, it says cannot automatically merge ??

**Comment by mananwason** [comment]
https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/ Please go through this to resolve conflicts from your code.

**Comment by YashKumarVerma** [comment]
A lot of thanks for this detailed tutorial.

**Comment by mananwason** [comment]
Sure :smiley: Happy to help!!

**Comment by YashKumarVerma** [comment]
sir, the tutorial says that $git status will tell the conflict, but it is saying all clean ?

**Comment by mananwason** [comment]
Could you do `git log` and send a screenshot.

**Comment by abishekvashok** [comment]
@YashKumarVerma since of you following manna Watson sir, but please fix the merge conflict I would advise you to close this PR and start a new one containing the updated commit(only one commit since you are having problems)

**Comment by abishekvashok** [comment]
And also close the earlier request by you

**Comment by YashKumarVerma** [comment]
sure.

**Pull request closed without merging**
