### PR TITLE
Address issue #375

### PR DESCRIPTION
**Pull request by mbj36**
Check this !

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://mbj36.github.io/gci15.fossasia.org

**Comment by abishekvashok** [comment]
Hey hey!  @mbj36 what's this? see the site you removed the "--- ---" lines, please re add them they are important for jekkyll.! :-1:

**Comment by mbj36** [comment]
@Abhi2424shek 
Ok i am going to add it 
Any issues with subscribe section ?

**Comment by abishekvashok** [comment]
Yes I guess, how are you going to know that if the user has entered an email (why not use html email tag or use javascript to validate it) Plus make these two test boxes required to submit the form (and NB: I AM NOT A MENTOR , JUST HELPING YOU OUT). Please resolve these issue and squash all your commits, let me know if you are having problems squashing. :) OK then @mbj36 why are you modifying the rest part of the page! Hey don't remove the "thank you for contributing" wrapper and also why are you modifying the gallery section?

**Comment by Abhi2424shek** [comment]
@mbj36 please resolve these issue and squash all your commits, let me know if you are having problems squashing. :) OK

**Comment by Abhi2424shek** [comment]
@mbj36 why are you modifying the rest part of the page! Hey don't remove the "thank you for contributing" wrapper and also why are you modifying the gallery section?

**Comment by yasoob** [comment]
Hey @Abhi2424shek kindly refrain from using all-caps (all capital letters). It is synonymous with shouting in online forums. Use **bold** instead. Moreover, kindly refrain from making a lot of noise. If you think that you forgot to mention something in your previous comment then edit it instead of making a new comment. :)

**Comment by Abhi2424shek** [comment]
@yasoob , I am just a kid looking to help others that's all :)

**Comment by yasoob** [comment]
I know. I am just trying to teach you how you can help others in a better way. You are doing a good job.

**Comment by abishekvashok** [comment]
@yasoob :) thanks for that plus why don't we delete all our use wanted comments and keep this PR clean. Deleted a lot of mine please do so and keep it clean

**Pull request closed without merging**
