### PR TITLE
Create ff logo

### PR DESCRIPTION
**Pull request by ciucur-daniel**

### CODE REVIEW

**Comment by ciucur-daniel** [comment]
[logo ff 5 i.zip](https://github.com/fossasia/gci15.fossasia.org/files/94401/logo.ff.5.i.zip)

#179

**Comment by SaptakS** [comment]
You need to change the logo in the code after forking this repo into your own account... Please follow basic instructions to use github..

**Comment by SaptakS** [comment]
Also, donot open another PR without closing the previous..

**Comment by ciucur-daniel** [comment]
what do you mean by changing the logo in the code?

**Comment by SaptakS** [comment]
Firstly you need to fork this repo into your account.. Then you need to add the image into the corresponding folder.. After that you need to modify the code as needed for adding the image to the website..

**Comment by SaptakS** [comment]
https://github.com/fossasia/gci15.fossasia.org/pull/481#issuecomment-172342000

**Comment by mariobehling** [comment]
Ok, I added it in the Privly folder. Cheers.

**Pull request closed without merging**
