### PR TITLE
Added Macedonian

### PR DESCRIPTION
**Pull request by 3phase**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://3phase.github.io/gci15.fossasia.org

**Comment by 3phase** [comment]
Hello, I have submitted a task in GCI, where am I supposed to provide a link to it?

**Comment by jigyasa-grover** [comment]
@3phase You need to provide the link of this PR in your task comments .

**Comment by 3phase** [comment]
Alright, thanks :)

**Pull request merged**
