### PR TITLE
Added blogs section as a part of GCI

### PR DESCRIPTION
**Pull request by abishekvashok**
Added section blogs as a part of GCI in a user friendly manner with minimal code(no js[except to load content] only css). Also emphasised to save page load time. @jig08 @roonyh @sudheesh001 @SaptakS @niccokunzmann @mananwason . Please review and accept(if possible) before any conflicts arrise. Here's the link to my task: https://codein.withgoogle.com/dashboard/task-instances/6251847782236160/?sp-page=1

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@Abhi2424shek Nice work. Merging!

**Comment by mariobehling** [comment]
The expectation in the task was that five blog posts are added into this section. Such a pity, it did not happen.

**Comment by codethejason** [comment]
@mariobehling Working on it right now. I will save the blog text in a js file and retrieve data from there.

**Comment by mananwason** [comment]
@mariobehling Six blog posts have been added already !!
screen shot 2016-01-21 at 10 52 36 am

**Comment by mananwason** [comment]
You need to click the section for this to expand.

**Comment by mananwason** [comment]
If you mean that you need the content as well, I'm sorry. I didn't know that had to be done.

**Comment by abishekvashok** [comment]
@mariobehling I did a click to view button that fetches data via ajax to save page load time! Please understand, I've added 6 blog posts! see the pic by @mananwason ! :)

**Pull request merged**
