### PR TITLE
Added Student Ryan Yeo

### PR DESCRIPTION
**Pull request by RyanYeo**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://RyanYeo.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@RyanYeo Resolve merge conflicts. [This](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) shall help.

**Comment by jigyasa-grover** [comment]
@RyanYeo  Use the same doc and squash your commits ? And then we shall merge :)

**Comment by RyanYeo** [comment]
some fatal error occured with my repo

**Pull request closed without merging**
