### PR TITLE
Added hello Php app to Gallery

### PR DESCRIPTION
**Pull request by abishekvashok**
Link to task: https://codein.withgoogle.com/dashboard/task-instances/5198382230405120/?sp-page=1. Please review and accept soon

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@Abhi2424shek GH Pages not working

**Comment by abishekvashok** [comment]
Can you help out @mananwason

**Comment by abishekvashok** [comment]
hey @mananwason http://abhi2424shek.github.io/ is loading then why is'nt http://abhi2424shek.github.io/gci15.fossasia.org

**Comment by abishekvashok** [comment]
help!

**Comment by roonyh** [comment]
@Abhi2424shek Change some file and push a commit to trigger a build in that repo.

And don't delete and recreate that repo again and again. You can both squash commits and resolve merge conflicts instead.

**Pull request closed without merging**
