### PR TITLE
Make Changes in Mentor and Student Section

### PR DESCRIPTION
**Pull request by iKhushPatel**
Insert the Photos of Mentor and Student
Make changes in HTML as per requirement
Little bit modification in CSS
And add entry into student.yml file

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://iKhushPatel.github.io/gci15.fossasia.org

**Comment by iKhushPatel** [comment]
Just Completed the Task. Please visit : http://ikhushpatel.github.io/gci15.fossasia.org

Please give APPROVE in Google Code in Task and also publish my details on official website : http://gci15.fossasia.org

Nice Experience to work with GitHub and learnt lots to work with Responsive Design. Thanks GCI and FOSSASIA

**Comment by sudheesh001** [comment]
Please resolve merge conflict.

**Comment by iKhushPatel** [comment]
Hey @mariobehling  Please refer Pull Request Link : https://github.com/fossasia/gci15.fossasia.org/pull/493

**Comment by jigyasa-grover** [comment]
@iKhushPatel As @sudheesh001 said, resolve merge conflicts before we can proceed. [This](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) might help. Let us know in case of any issues.

**Comment by roonyh** [comment]
@iKhushPatel More importantly, you don't need to change anything in the index.html. Just edit `students.yml` file. And add your photo.

The syntax in the html file are used by jekyll to build the website. Its used in github pages.

If you like you can [learn more](https://help.github.com/articles/using-jekyll-with-pages/)

**Comment by iKhushPatel** [comment]
@roonyh  OK . Thanks. Now i understand

I will change soon.

**Comment by iKhushPatel** [comment]
@roonyh  So now i want to replace the original index.html ?

**Comment by roonyh** [comment]
@iKhushPatel Yes. And since this PR has conflicts. Its better if you start over again. Refer https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md

**Comment by jigyasa-grover** [comment]
Updates @iKhushPatel ? Feel free to ask questions, if any.

**Comment by Sharatsa** [comment]
Hey @iKhushPatel, I viewed you work.
No need to modify the index.html, hover.css, scroll.css or stylesheet.css.
Start Over again with a new fork, delete the prev. one.
Just add your name and bio in the students.yml file, Add your photo in img/students folder and commit changes. Make a new PR. That's all you need to do.

**Comment by jigyasa-grover** [comment]
@iKhushPatel Closing this.

**Pull request closed without merging**
