### PR TITLE
converted all .png photos to .jpg photos

### PR DESCRIPTION
**Pull request by imharrymargalotti**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://imharrymargalotti.github.io/gci15.fossasia.org

**Comment by imharrymargalotti** [comment]
@mananwason my demo link wouldn't load, but i believe this is all correct

**Comment by codethejason** [comment]
@imharrymargalotti It seems like you have an empty `gci15.fossasia.org` repository. If you want the automatic demo link to work, you can rename your fork to `gci15.fossasia.org`.

**Comment by imharrymargalotti** [comment]
@codethejason Thanks! i didn't see that

**Comment by abishekvashok** [comment]
Would be best if you could post the current and the updated code insights screen shots as currently the speed is measured by the rating on insights here. Got it @imharrymargalotti

**Comment by abishekvashok** [comment]
Please resolve the conflicts see here https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md for more info about how to resolve conflicts @imharrymargalotti .

**Comment by jigyasa-grover** [comment]
@imharrymargalotti Working on this ?

**Comment by imharrymargalotti** [comment]
It's been done for a while, I could update it in a new
PR to convert any newly added photos

**Comment by jig08** [comment]
Cool. So am closing this PR :)

**Comment by prwatch** [comment]
DEMO: http://imharrymargalotti.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
Could you remove the merge commit ?

**Comment by abishekvashok** [comment]
@jig08 no conflicts now!

**Comment by mananwason** [comment]
@Abhi2424shek The merge commit still exists.

**Comment by abishekvashok** [comment]
This is what I see @mananwason 
image

**Comment by jigyasa-grover** [comment]
@Abhi2424shek There are no merge conflicts but there is a commit namely `Merge remote-tracking branch 'refs/remotes/fossasia/gh-pages' into gh-pages` which needs removal.

**Comment by abishekvashok** [comment]
@jig08 got it.

**Comment by imharrymargalotti** [comment]
@mananwason Do you want me to squash it?

**Pull request closed without merging**
