### PR TITLE
Task Completed

### PR DESCRIPTION
**Pull request by iKhushPatel**
Thanks to Mentors, FOSSASIA, Google and GitHub to provide an
Opportunity.  Love to explore Open source.

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://iKhushPatel.github.io/gci15.fossasia.org

**Comment by iKhushPatel** [comment]
Hey @SaptakS  I have resolved the conflicts Issue. 

What is Next ?

**Comment by iKhushPatel** [comment]
@SaptakS  What is Next ? Please suggest me.

**Comment by iKhushPatel** [comment]
@jig08 and @mariobehling   I have fixed the merge conflict issue. Please suggest me What is Next ?

**Comment by sudheesh001** [comment]
@iKhushPatel You need to work on the design changes so that the task can be approved, it's a great start by adding your information. Please fix a task in the list of tasks here https://github.com/fossasia/gci15.fossasia.org/issues

**Pull request merged**
