### PR TITLE
Fixed Issue #91, #96, Added Student Gallery

### PR DESCRIPTION
**Pull request by Meta-Maxim**
G+ Widget now scales to landscape mode in mobile. Youtube size is fixed.

### CODE REVIEW

**Comment by mariobehling** [comment]
There are merge conflicts. Please resolve it.

**Comment by Meta-Maxim** [comment]
@mariobehling Done.

**Comment by Meta-Maxim** [comment]
Ok, this pull now also adds a student gallery section! Next I'll make gallery images show in a slideshow when clicked.

**Comment by PiotrKowalski** [comment]
If you are working with media section could you repair padding on mobile phones?
screenshot_2015-12-20-13-48-53
screenshot_2015-12-20-13-49-01_1450615780373

**Comment by Meta-Maxim** [comment]
@PiotrKowalski I'm not working on the Media section, I'm working on the Student Gallery and after that publications. I just fixed a G+ bug since I was the one who added it. Once this is pulled you can work on media if you want.

**Pull request merged**
