### PR TITLE
Changes in design

### PR DESCRIPTION
**Pull request by pythad**
- Made the design flat, no shadows
- Changed layout to be responsive
- Added social links support
- Implemented more elegant footer

[DEMO](http://pythad.github.io/gci15.fossasia.org/)

### CODE REVIEW

**Comment by mariobehling** [comment]
Looks great. Next step: please keep or re-implement some of the work of former students
- rounded pictures
- grey, blue, yellow background (it is a student site, so it is ok to use some color)

**Comment by pythad** [comment]
@mariobehling, [it's ready](http://pythad.github.io/gci15.fossasia.org/). I don't find having many colors too cool, but maybe you are right and it's okay for this kind of web page.

**Comment by mariobehling** [comment]
Looks good. If you have time, please change green to dark grey in the back ground. Good work!

**Comment by mariobehling** [comment]
Looks like not all your changes are included in the PR. Please check http://gci15.fossasia.org

**Comment by mariobehling** [comment]
Or maybe cloudflare needs some time to serve the updated files.

**Comment by pythad** [comment]
@mariobehling, it looks like site hasn't been updated with new css, I checked it by viewing source code of the web page, but css files in the repo are okay. It's strange...

**Comment by mariobehling** [comment]
Yeah. Not sure, what happened. I am tight on time, but if you find out, please definitely let me know.

**Pull request merged**
