### PR TITLE
Added FOSSASIA newsletter to site. Closes #375

### LINKED ISSUE #375: Add FOSSASIA newsletter to site
Sample code of the newsletter is below:

```
<form action="http://news.fossasia.org/subscribe" method="POST" accept-charset="utf-8">
    <label for="name">Name</label><br/>
    <input type="text" name="name" id="name"/>
    <br/>
    <label for="email">Email</label><br/>
    <input type="text" name="email" id="email"/>
    <br/>
    <input type="hidden" name="list" value="A8fchTRvBw2wap1ojIfjyQ"/>
    <input type="submit" name="submit" id="submit"/>
</form>
```

### PR DESCRIPTION
**Pull request by yasoob**
One more issue bites the dust :+1: Congrats team!

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://yasoob.github.io/gci15.fossasia.org

**Comment by yasoob** [comment]
The website is already very heavy and contains a **lot** of content. IMO this is a much better way to put the newsletter form on the website for two reasons:
- It does not increase the length of the html document
- It get's the attention of the reader (The slide-in can be closed easily)

**Comment by yasoob** [comment]
@jig08 and @mananwason kindly let me know what you guys think about this implementation.

**Comment by jigyasa-grover** [comment]
It seems to hide the social media links to FOSSASIA accounts ...

**Comment by yasoob** [comment]
You can close the newsletter div if you want to look at social media links. There is a small cross at the top-left of the div.

**Comment by jigyasa-grover** [comment]
Yes, I know.

**Comment by yasoob** [comment]
What should be done in your opinion then?

**Comment by codethejason** [comment]
I like the newsletter slide-in you have now, but I agree with @jig08 that it should not cover the social media icons as they fit with the "outreach" theme.

**Comment by mananwason** [comment]
@yasoob I agree with @jig08 and @codethejason. What if you move the newsletter to the left and fit it under Other links? I think that should work.

**Comment by jigyasa-grover** [comment]
@mananwason @codethejason @yasoob 
Yes, That could be done. Or maybe , what if it pop ups from the bottom ?

**Comment by yasoob** [comment]
@jig08 what do you mean by "pop ups from the bottom"? Can you kindly elaborate?

**Comment by mananwason** [comment]
@jig08 I think a pop up would not be feasible in the space we have here.

**Comment by jigyasa-grover** [comment]
@mananwason @yasoob Umm.. okay . So what else could be done ?

**Comment by yasoob** [comment]
I am working on a fix. The newsletter div will be placed above the orange
footer. If everything goes well I will send a PR tonight.

**Comment by jigyasa-grover** [comment]
Sure !

**Pull request closed without merging**
