### PR TITLE
Added my pic and credentials

### PR DESCRIPTION
**Pull request by sanjaytharagesh31**
I have added my photo in img/students/sanjay.jpg.
My credentials at _data/students.yml

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://sanjaytharagesh31.github.io/gci15.fossasia.org

**Comment by roonyh** [comment]
Good job!

**Comment by sanjaytharagesh31** [comment]
Have I completed the task?

**Comment by roonyh** [comment]
@sanjaytharagesh31 Yes! Please accept our invitation to join FOSSASIA GCI Students team.

**Pull request merged**
