### PR TITLE
Guneet Singh

### PR DESCRIPTION
**Pull request by itsguneetsingh**
Please merge it

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Guneetconvent2002.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@Guneetconvent2002 There are conflicts. I am not able to merge. Use [This](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) for reference on how to solve conflicts. Cheers!

**Comment by jigyasa-grover** [comment]
@Guneetconvent2002 Kindly follow the instructions at [GIT.md](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) to resolve merge conflicts. There isn't any need to close PRs (wrt PR #692 #640 ), you can rectify your previous ones as well.

**Comment by jigyasa-grover** [comment]
Closing this.

**Comment by mariobehling** [comment]
@Guneetconvent2002 Please make a pull request that does not have merge conflicts before tomorrow. So we can accept your task in GCI. Thank you!

**Pull request closed without merging**
