### PR TITLE
New image added

### PR DESCRIPTION
**Pull request by PawelKowalski99**

### CODE REVIEW

**Comment by roonyh** [comment]
@asplia Good job! I just merged a PR which made your PR to conflict :( Could you please rebase? Let me know if you have any trouble. Thanks!

**Comment by PawelKowalski99** [comment]
I don't know what you mean. Sorry

**Comment by roonyh** [comment]
Can you try instructions from https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md ?

**Comment by PawelKowalski99** [comment]
http://scr.hu/323u/rrfqh
 http://scr.hu/323u/kknub
 I am having a little problem http://scr.hu/323u/j9rcn

**Comment by PawelKowalski99** [comment]
Please check it. I think I did it

**Comment by mananwason** [comment]
Please squash commits @asplia

**Comment by mananwason** [comment]
@mariobehling the commits aren't squashed. 2 out of the 3 commits do nothing.

**Comment by PawelKowalski99** [comment]
okay

**Comment by PawelKowalski99** [comment]
but what does it mean?

**Comment by mananwason** [comment]
@asplia squashing commits means clubbing similar commits into one. See this http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request. I am reverting the merge for now @mariobehling.

**Comment by PawelKowalski99** [comment]
so I have to squash it into one "201 to 202"?

**Comment by mananwason** [comment]
No on your machine do git rebase -i HEAD~3 and then in the interactive mode select squash for the last 2 commits while keeping the first one as it is. Then just enter the relevant commit message. You're good to go.

**Comment by PawelKowalski99** [comment]
Can I delete this Sarah before me because she is above on the site?

**Comment by mananwason** [comment]
Can you point out where in the code tab of this PR. Right now I don't get why would you want to delete someone else's details.

**Comment by PawelKowalski99** [comment]
http://scr.hu/323u/5qz79

http://scr.hu/323u/y9py4

**Comment by PawelKowalski99** [comment]
I think I acidentally added one

**Comment by mananwason** [comment]
Yeah you did. No issues, get rid of it, commit again and squash all the commits into one.

**Comment by PawelKowalski99** [comment]
so Should I delete it or not? there are two difference text in code take a look again

**Comment by mananwason** [comment]
yeah I saw. Sarah has been added twice. Delete the one you added, commit again and squash all the commits into one.

**Comment by roonyh** [comment]
@mananwason Could you maybe add some instructions to https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md on how and why to squash commits? Instructions should be specific to our repo. If you can review the stuff I added also. Some students who are new to git have troubles with it. And this will be helpful. Thanks much :)

**Comment by mananwason** [comment]
Good idea @roonyh. I'll add those instructions ASAP.

**Comment by PawelKowalski99** [comment]
I am really sorry but I am not able to do it. I can't understand squashing

**Comment by roonyh** [comment]
@asplia ok, don't worry about squashing, just do the correct changes.

1) `git reset --hard upstream/master`
2) Do your changes. (Add your photo and name and stuff)
3) `git push -f pawel`

**Comment by PawelKowalski99** [comment]
Is it right?

**Comment by mananwason** [comment]
@asplia Your commit is not here. You need to create a PR again from your fork.

**Pull request merged**
