### PR TITLE
modified the games section. Simplified it and made it fast. closes #377

### LINKED ISSUE #377: Add a lightweight section "Games" to the site or improve it
- Move all student projects of games into a special dedicated section
- Ensure that the area is loading fast

### PR DESCRIPTION
**Pull request by yasoob**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://yasoob.github.io/gci15.fossasia.org

**Comment by yasoob** [comment]
Both of these commits close two separate issues so IMO we should not squash them together.

**Comment by jigyasa-grover** [comment]
I am not really sure if this design should be included for the "Games" section.

**Comment by yasoob** [comment]
Well @mariobehling said not to use the same design as the gallery so I am not sure what else I can do. Any ideas?

**Comment by yasoob** [comment]
I had forgot to change the background color of the games section. Kindly check and let me know if this is any better.

**Comment by mananwason** [comment]
Looks good @yasoob :+1:

**Pull request merged**
