### PR TITLE
Gh pages

### PR DESCRIPTION
**Pull request by naveenbalachandran**
as asked by the privly team here is the low res version of my tshirt design

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://naveenbalachandran.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@naveenbalachandran Can you give the link to the task?

**Comment by naveenbalachandran** [comment]
https://codein.withgoogle.com/dashboard/task-instances/5458992859971584/?sp-page=1

**Comment by naveenbalachandran** [comment]
Thank you

**Pull request merged**
