### PR TITLE
Added details about myself (Somya Upadhyay)

### PR DESCRIPTION
**Pull request by somyaupadhyay**
Added my blog, social networking profiles and bio.

### CODE REVIEW

**Comment by mananwason** [comment]
@somyaupadhyay Can you include you image in this PR only and then squash the commits?

**Comment by somyaupadhyay** [comment]
I tried to achieve that but I am facing some difficulty in that. Could you please guide?

**Comment by mananwason** [comment]
Sure. Tell me what issues are you facing?

**Comment by rkgudboy** [comment]
Checks passed, Showing no conflicts. Merging

**Comment by mananwason** [comment]
@rkgudboy Did you read the comments?

**Comment by mananwason** [comment]
@rkgudboy There was no image in the PR. There's a broken link now :confused: 
screen shot 2016-01-25 at 5 43 03 pm

**Comment by mananwason** [comment]
@rkgudboy Please check before merging in the future. I have fixed it for now.

**Comment by rkgudboy** [comment]
Hi @mananwason I apologize, Sorry for the trouble. I missed the comment.

**Comment by rkgudboy** [comment]
I began merging on seeing no conflicts, but due to connection lag, I could not cancel it, once you commented anyways thank you for resolving the problem. :)

**Comment by mananwason** [comment]
Sure no issues :smile:

**Pull request merged**
