### PR TITLE
Site redesign

### PR DESCRIPTION
**Pull request by pythad**
I've tried to redesign the site using MeterializeCSS. It's flat and simple now. Also I tried to create boxes for students and mentors profiles as no one can add any information now. Take a look at it and say what you think. [Demo](http://pythad.github.io/gci15.fossasia.org/)

### CODE REVIEW

**Comment by sudheesh001** [comment]
@pythad The demo website looks really good, I've got a few suggestions.
- Clicking the links `Our mentors` or `Our students` on the top right corner directly jumps to required sections. Making the transition move smoother would be better. a general way to do this with jQuery is to use `.animate()`.
- In the 

```
Name
<content>
```

It almost looks like both of them are having the same size, emphasize on the name, increase the font size for that, add a little margin between the name and the content that is being written.
How about changing the `Card` layout of materialize to use this http://materializecss.com/cards.html

Follow the same layout that you're following now, image to the left and the heading and content to the right.

**Comment by pythad** [comment]
I've implemented what you mentioned.
- Added smooth-scrolling
- Made the page brighter
- Redesigden profile block 
  - big fonts
  - more elegant
  - more addaptive
  - using cards now

[Demo](http://pythad.github.io/gci15.fossasia.org/)

**Comment by sudheesh001** [comment]
@pythad Great progress, I have a few more suggestions, Here's what someone might see as a user
- To see the list of mentors and students one would have to scroll through a very long list, It'd be nicer if there are 3 cards or so that's maintained in each row showing 3 mentors and 3 students at once.

**Comment by hvardhanx** [comment]
Great going @pythad . :)

**Comment by pythad** [comment]
Yes, it seems that it will take much place to show all people. Speaking about more that 1 card in a row, what do we need to do with blocks of different height? In my opinion it will mess up if bocks will be of different height and even if they are aligned. Do we need to align them somehow or just give them fixed size, like [teamtreehouse library](https://teamtreehouse.com/library) did?

**Comment by SaptakS** [comment]
The way teamtreehouse did is good enough. You can follow that.

**Comment by pythad** [comment]
- Made 3 cards layout. The hight of a card is `355px`, I think it's enough to provide some basic information.
- Added a footer with useful links

[Demo](http://pythad.github.io/gci15.fossasia.org/)

**Comment by roonyh** [comment]
@pythad Demo looks great. Can you try and add the slider of http://gci15.fossasia.org/ to your site. At the moment the content section of http://gci15.fossasia.org/ is empty and your _our mentors_ and _our students_ sections will fit there great. Put your header at the top of the slider. I don't know how material design will fit with the slider but i think it'll work. What do you think?

**Comment by mariobehling** [comment]
@pythad This is really fantastic. As many students signed up to collaborate on this task, let's split changes into smaller commits. Right now, we get "This branch has conflicts that must be resolved". The reason is, that there are other commits and contradicting code. 

Maybe let's start with a photo first? 

In any case, your contribution is great and we would be happy to see this task as solved from your side. Please let me know, what are your ideas.

All the best!

**Comment by pythad** [comment]
@mariobehling, Okay I've added one more commit and implemented all the suggestions. Here is the [demo](http://pythad.github.io/gci15.fossasia.org/). It's almost ready to use, at least for some staging area. I am not sure how it's possible to split the site into smaller commits. I think it's just possible merge the latest version now. What do you think and suggest us to do?

**Comment by mariobehling** [comment]
Hi, this looks great, but I am not really sure, what students are supposed to write in the text area. Do you have a more simple option? Maybe only a photo similar to last year or to the speakers at http://2015.fossasia.org/#speakers

**Comment by pythad** [comment]
@mariobehling, It was supposed to be an area for links, but as I added little footers there is no need for it now, you're right. Take a look at [this version](http://pythad.github.io/gci15.fossasia.org/)

**Comment by mariobehling** [comment]
Great, could you take out the squares as well and make a PR?

**Pull request closed without merging**
