### PR TITLE
Added light out data.

### PR DESCRIPTION
**Pull request by antoniomdk**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://antoniomdk.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@antoniomdk Please solve conflicts.

**Comment by jigyasa-grover** [comment]
@antoniomdk Updates pls ?

**Comment by antoniomdk** [comment]
I thought The contest had ended and I could not do anything more

**Comment by mananwason** [comment]
you can contribute even after the contest is over, if you want to !! :smile:

**Comment by jigyasa-grover** [comment]
@antoniomdk You surely can, throughout the year too !

**Comment by antoniomdk** [comment]
perfect, i am going to solve the conflicts

**Comment by mananwason** [comment]
Great :+1:

**Comment by antoniomdk** [comment]
I do not have write access. How can I resolve the conflicts?

**Comment by jigyasa-grover** [comment]
Well, you don't need it.
Just follow the instructions given [here](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md).

**Comment by antoniomdk** [comment]
I read it but I do not know how to solve them. I can fork again or squash commit but not solve conflicts.

**Comment by jigyasa-grover** [comment]
What kind of issue are you facing exactly ?
What does the error show ?

---

Try starting afresh with a clean fork ?

**Comment by antoniomdk** [comment]
Again? I create a clean fork only to upload this commit. I do not know the error. I uploaded the commit and it can be merged.

**Comment by mananwason** [comment]
@antoniomdk How did you solve commits? I can assist you by telling where you went wrong. Cheers!

**Pull request closed without merging**
