### PR TITLE
Made navbar fit any screen size.

### PR DESCRIPTION
**Pull request by Meta-Maxim**
Makes the navbar more colorful and also scale to different screen sizes.
Squashed all the commits.

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://MaxBorsch.github.io/gci15.fossasia.org

**Comment by Meta-Maxim** [comment]
@jig08 Here is my new pull request for the old update.

**Comment by jigyasa-grover** [comment]
@MaxBorsch Kindly refer Issue #394 , A new design was thought of. Could you modify accordingly ?

**Comment by Meta-Maxim** [comment]
@jig08 Ok, I'll add the changes.

**Pull request closed without merging**
