### PR TITLE
My info for Fossasia GCI 2015 website.

### PR DESCRIPTION
**Pull request by S-ulphuric**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://S-ulphuric.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@S-ulphuric Resolve merge conflicts.

**Comment by jigyasa-grover** [comment]
@S-ulphuric Also squash commits.

This might help https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md

**Comment by S-ulphuric** [comment]
Whenever I'm trying to squash my commits its giving me an error. Please help me here.

**Comment by jigyasa-grover** [comment]
What error does it show @S-ulphuric ?

**Comment by S-ulphuric** [comment]
screenshot

**Comment by mananwason** [comment]
@S-ulphuric What is your default text editor? If it is notepad, please change it to Notepad++ or Sublime

**Comment by S-ulphuric** [comment]
It is sublime.

**Comment by mananwason** [comment]
@S-ulphuric This is most probably due to your choice of editor. It would be nice if you could change your editor using http://stackoverflow.com/questions/10564/how-can-i-set-up-an-editor-to-work-with-git-on-windows

**Pull request closed without merging**
