### PR TITLE
I added my picture and details

### PR DESCRIPTION
**Pull request by julianjaeger**

### CODE REVIEW

**Comment by samarsault** [comment]
Great going !
But there is an error in the YAML. Please remove the whitespace before `- name`.

**Comment by seadog007** [comment]
BTW, you don't need to write the subject in your commit message.

**Comment by tradzik** [comment]
@julianjaeger And please [squash the commits](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) after submitting your changes (these, which @samarjeet27 suggested)

**Comment by julianjaeger** [comment]
Hello, I wanted to ask what you mean with "squash the commits".

**Comment by seadog007** [comment]
Or you can just reset to HEAD^, make the change, and recommit again

**Comment by tradzik** [comment]
@julianjaeger It means to connect all the commits into one. I gave you instructions in the link in my post above.

**Comment by hvardhanx** [comment]
Please resolve the conflicts.

**Comment by Meta-Maxim** [comment]
@julianjaeger Could you make your image 300x300 please?

**Comment by mananwason** [comment]
@julianjaeger please resolve conflicts too :smile:

**Comment by mananwason** [comment]
Since there is no response from @julianjaeger. I am closing this.

**Pull request closed without merging**
