### PR TITLE
Gh pages

### PR DESCRIPTION
**Pull request by sarahgreisdorf**
# Conflicts:
# _data/students.yml

### CODE REVIEW

**Comment by pythad** [comment]
@sarahgreisdorf hi, we use only twitter nickname in `students.yml`. Your one has to look like `twitter: sarahgreisdorf`. Could you change it?

**Comment by Meta-Maxim** [comment]
@sarahgreisdorf Also resize your image to 300x300 please.

**Comment by sarahgreisdorf** [comment]
Did both of those things.  All set?

**Comment by codethejason** [comment]
You have to resolve some merge conflicts. Do that by updating from `fossasia/master`.

**Comment by sarahgreisdorf** [comment]
Fixed!

**Pull request merged**
