### PR TITLE
Remove untracked files and added myself

### PR DESCRIPTION
**Pull request by codethejason**

### CODE REVIEW

**Comment by Meta-Maxim** [comment]
@codethejason Found a solution, you can remove tracked files and then upload it. I'll have it fixed in my next pull, don't worry. Also apparently what was wrong with my gitignore is that it wasnt the right encoding and git doesn't like that .-.

**Comment by codethejason** [comment]
@MaxBorsch That's why I deleted the files that weren't supposed to be tracked but didn't you say that Jekyll automatically regenerates them when you PR? The current gitignore worked for me after I deleted those files from my local system.

**Comment by Meta-Maxim** [comment]
@codethejason It does, but it does that after the pull completes, so the .gitignore takes effect first. If it's working then nvm, all is good.

**Comment by seadog007** [comment]
Please resolve the conflicts

**Comment by codethejason** [comment]
It's up to date.

**Pull request closed without merging**
