### PR TITLE
Added 3 of my projects to GCI website

### PR DESCRIPTION
**Pull request by abishekvashok**
Added 3 of my projects to GCI website as a part of GCI task. Please accept it @sudheesh001 @mananwason @jig08 @nikunjness @roonyh @mariobehling .

Link to task:  https://codein.withgoogle.com/dashboard/task-instances/6468600403591168/?sp-page=1

Please accept it before conflicts arise.

-Enjoying last working days at GCI

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@Abhi2424shek You need to add your projects here[https://github.com/fossasia/fossasia-gci15] as well.

**Comment by mananwason** [comment]
I'll merge this for now but the task can be approved when you add your projects to the fossasia-gci15 repo. Cheers!

**Comment by abishekvashok** [comment]
Ok got it cheers @mananwason  and it would be best if you could follow upon fb

**Comment by mananwason** [comment]
Follow upon what @Abhi2424shek?

**Comment by abishekvashok** [comment]
follow upon my messages in facebook @mananwason

**Pull request merged**
