### PR TITLE
Added myself

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by seadog007** [comment]
Hi, @funkyDunks, there are few problems in your commit.
First, your blog link didn't include `http://` or `https://`
Second, you don't need to delete the part that you don't use.

You can reset the commit and recommit it by following command

``` bash
git reset HEAD^
---- Fix your mistake ----
git add -A
git commit -am "Added new student"
git push -f
```

So you don't need to
- delete the repo and re-fork it
- close this PR and re-create a PR

**Comment by funkyDunks** [comment]
I reduced the image sizes in my PR, so the page should load a bit faster

**Comment by roonyh** [comment]
@funkyDunks This looks fine. And thanks for thinking about reducing image sizes. But It was done in recently merged PR and now this conflicts with master. Can you please resolve and commit again? Just add your image and info for now. Thanks!

**Comment by Meta-Maxim** [comment]
@funkyDunks Make sure your profile pic is 300x300.

**Comment by ghost** [comment]
Sorry, I made these a changes a while ago... Will fix later

**Pull request closed without merging**
