### PR TITLE
add student:vicchen0502

### PR DESCRIPTION
**Pull request by vicchen0502**
add student:"vicchen0502"

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://vicchen0502.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@vicchen0502 Please resolve conflicts

**Comment by jigyasa-grover** [comment]
@vicchen0502 [This](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) might help.

**Comment by jigyasa-grover** [comment]
@vicchen0502 Working on this ?
Closing for now...

**Pull request closed without merging**
