### PR TITLE
Added Issues section. Solves : https://github.com/fossasia/gci15.fossasia.org/issues/559

### PR DESCRIPTION
**Pull request by abishekvashok**
Added issue's section as part of GCI task to resolve issue https://github.com/fossasia/gci15.fossasia.org/issues/559. Hurray :)

And here's the link to my task: https://codein.withgoogle.com/dashboard/task-instances/6099260126789632/?sp-page=1

Please accept soon before conflicts arrise @mananwason @jig08 @mariobehling @roonyh.

Last working days enjoying at GCI

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@Abhi2424shek First of all the reload button when there are no issues doesn't work. Also, we don't want a design where we have to click on something and then the issues are displayed. Please make it visible without clicking there. Thirdly, please try to parse and display the issue with the markdown used originally. Right now it doesn't parse the markdown and displays the raw text. 

Please fix these issues then we can approve and merge! Cheers!

**Comment by abishekvashok** [comment]
Firstly the reload button works it calls the function it does'nt seem to work because there are not issues . I would add a new PR as my client doesnot support squashing it creates a new commit evertime I squash so please wait.

**Comment by abishekvashok** [comment]
@mananwason I removed the extra text as some of them never had the body and also the read more button would be non-neccessary. So please accept it and also now it loads on page load. But that would increase load time! Anyway enjoying here's the updated PR link: https://github.com/fossasia/gci15.fossasia.org/pull/605

**Pull request closed without merging**
