### PR TITLE
resized all student photos

### PR DESCRIPTION
**Pull request by imharrymargalotti**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://imharrymargalotti.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
Nice work @imharrymargalotti !! Cheers :smile: Are there any images still left that are greater than 240x240?

**Comment by imharrymargalotti** [comment]
nope! every image is good, do you want me to convert the rest of the .png pictures to .jpg as well? @mananwason

**Comment by mananwason** [comment]
Great! Yes you can go ahead @imharrymargalotti. Png's are of a significantly bigger size than Jpg's and having all Jpg's would improve the speed of the site. :grinning:

**Pull request merged**
