### PR TITLE
Greatly improved the newsletter prompt. 

### PR DESCRIPTION
**Pull request by yasoob**
Now it does not cover any text in the footer. @mananwason & @jig08 What do you guys have to say about this implementation?

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://yasoob.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
Yes, looks better than all the previous implementations.

**Comment by mananwason** [comment]
@yasoob Looks nice but when scrolling back up, the hiding transition is not smooth like it's being forcefully being dragged off the page :stuck_out_tongue: . Also it hides the fossasia badges if we scroll upwards. If you can fix that, we're good to go !!. Anyways, Nice work :smile:

**Comment by yasoob** [comment]
I will fix it shortly :)

**Comment by yasoob** [comment]
Hey @mananwason With _badges_ do you mean this G+ div? 
screenshot from 2016-01-22 18 05 39

**Comment by yasoob** [comment]
Hey @mananwason I have improved the slide-out animation. Now it does not appear to be forced. I also modified the distance after which the newsletter div appears. I am sure that it will not hide the fossasia badges now :+1: 

Kindly check it and let me know if it is good to go! :smile:

**Comment by jigyasa-grover** [comment]
@yasoob I am not able to open the website at http://yasoob.github.io/gci15.fossasia.org. Idky but its taking forever to load, despite a very good internet connection.

**Comment by yasoob** [comment]
Hey @jig08 It is working fine on my side :confused:  http://yasoob.me/gci15.fossasia.org/ GitHub pages was having some issues earlier today. There was some DNS related issue. I guess that might be the cause of the delay on your side. Can you try again?

**Comment by mananwason** [comment]
@yasoob Nice work. Looks good now !! 
@jig08 it's working on my pc as well

**Comment by jigyasa-grover** [comment]
Working fine now. Yes, there was an issue with DNS, was happening with other gh-pages too ...

**Pull request merged**
