### PR TITLE
Reduced box-shadow of tweets-div. Closes #662

### LINKED ISSUE #662: Fix shadow for tweets from loklak
Looks like the tweets holder is at a greater height than the rest. 
screen shot 2016-01-24 at 7 22 21 pm

### PR DESCRIPTION
**Pull request by yasoob**
Closes #662

@mananwason Kindly check and let me know if the intensity of `box-shadow` is fixed. It seems better to me :smile:

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://yasoob.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@yasoob don't see much change. Look at the pic in the badge just below the tweets section. There seems to be some effect of the shadow from the tweet section.

**Comment by yasoob** [comment]
Let me recheck :+1:

**Comment by mananwason** [comment]
awesome :+1:

**Comment by jigyasa-grover** [comment]
@yasoob Updates Pls ? :)

**Comment by yasoob** [comment]
Hey @jig08 Sorry. I was a bit preoccupied with some other important work. I will push an update today. :)

**Comment by jigyasa-grover** [comment]
No issues @yasoob :)

**Comment by prwatch** [comment]
DEMO: http://yasoob.github.io/gci15.fossasia.org

**Comment by yasoob** [comment]
Hey @mananwason @jig08 I have solved the box-shadow issue. Kindly verify it :)

**Pull request merged**
