### PR TITLE
Gh pages

### PR DESCRIPTION
**Pull request by naveenbalachandran**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://naveenbalachandran.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@naveenbalachandran What is this PR for ? Doesn't seem valid, I am closing this.

**Comment by naveenbalachandran** [comment]
Pr?

**Comment by jigyasa-grover** [comment]
PR == Pull Request :)

**Pull request closed without merging**
