### PR TITLE
Improved lights out section

### PR DESCRIPTION
**Pull request by jmurzaku**
Added a switch to lights out section while preserving heading style

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://JamMurz.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@JamMurz The button seems to be stuttering. Please check and try to make it smooth. Also please improve the position of the button.  Otherwise looks good. Cheers! :smile:

**Comment by jmurzaku** [comment]
@mananwason i fixed it so that the h1 is now centered like the rest of the website. All commits are squashed too

**Comment by jigyasa-grover** [comment]
Ah yes, Seems better !

**Pull request merged**
