### PR TITLE
added my info

### PR DESCRIPTION
**Pull request by AvramPop**
personal photo and data

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://AvramPop.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@AvramPop Resolve merge conflicts.

**Comment by AvramPop** [comment]
where are them?

**Comment by jigyasa-grover** [comment]
Right here, in this PR.

**Comment by AvramPop** [comment]
that lack of 2 newlines, you mean?

**Comment by jigyasa-grover** [comment]
@AvramPop Nope. 
You'll need to update your branch with new commits from master, resolve those conflicts and push the updated/resolved branch to GitHub.

**Pull request closed without merging**
