### PR TITLE
Loklak Heatmap working again. Closes #552

### LINKED ISSUE #552: Fix section issue e.g. Student Gallery and Loklak Heatmap do not work anymore
- [x] student gallery - cannot click on works, no more bottom list, forward/back link does not work
- [ ] student gallery - please move items like games and geolocation projects to other areas
- [x] heatmap - show map and search button again

### PR DESCRIPTION
**Pull request by yasoob**
Search for "tim" to get more results :+1: 

The other issues listed in #552 have already been closed by me.

Moreover, can this PR be used for [this](https://codein.withgoogle.com/tasks/6323393175486464/?sp-is_beginner=False) task? :smile:

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://yasoob.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
Go ahead @yasoob. You can use it for the task.

**Comment by yasoob** [comment]
Thanks. But I am still waiting for the acceptance of [this](https://codein.withgoogle.com/dashboard/task-instances/4646726010929152/?sp-page=1) task. :disappointed:

**Comment by mananwason** [comment]
Accepted @yasoob !! Go ahead :smile:

**Comment by yasoob** [comment]
Thanks! Well.... If it is appropriate then can you kindly accept [this](https://codein.withgoogle.com/dashboard/task-instances/6496393271181312/?sp-page=1) task as well? :smile_cat:

**Comment by mananwason** [comment]
Done :smile: All the best!

**Comment by yasoob** [comment]
Thanks! :dancer:

**Pull request merged**
