### PR TITLE
Added timestamp & twitter name on webtweets

### PR DESCRIPTION
**Pull request by Yathannsh**
- I have added a timestamp & a twitter name display on web-tweets.
- Also changed the profile-picture to be round for a better display.
- Changed the CSS file http://gci15.fossasia.org/stylesheets/loklak.css, to be  before the external javascript. Following the suggestion made in #367

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Yathannsh.github.io/gci15.fossasia.org

**Comment by mariobehling** [comment]
Hi, I think there is a real misunderstanding going on and I am not sure, when it started. It looks like the feed now shows anything related to loklak. As a matter of fact it should be showing tweets from FOSSASIA.

Secondly, we don't really want to see twitter here, we want to see loklak integrated here. There is an example what direction we are aiming for here: https://github.com/fossasia/fossasia-loklak-webtweets

It would be great, if you could help to integrate loklak and fix the tweets showing up here to show the relevant information about "FOSSASIA". loklak is meant to be a tool not the content of tweets. Thank you.

**Comment by Yathannsh** [comment]
@mariobehling , I have now modified the feed to display tweets from FOSSASIA. 
I am not sure about what you mean by integrating Loklak here :sweat: 
The section uses the Loklak API to fetch tweets what more is it to be done?
It would be great if you could elaborate a bit more. Thanks!

**Comment by sudheesh001** [comment]
@Yathannsh I believe what needs to be done here is using the loklak API from the search for fossasia and display them all rather than anything related to loklak, the main aim being removing the usage of twitter api and use loklak instead. I would ask @mariobehling to confirm.

There's a lot of amazing design changes that you could make as a part of this task. We look forward to seeing you here.

**Comment by Yathannsh** [comment]
@sudheesh001 I don't see anything related to Loklak being display on the feed (Or maybe I am misunderstanding this) . The twitter API has already been scrapped and the feed uses Loklak to query and fetch tweets. I did make some design & utility enhancements along with changing the query to display tweets from FOSSASIA instead of displaying tweets which have a mention of FOSSASIA as @mariobehling  required them to be. 
Out of the changes that the feed required the following have been made: 
1) The twitter API has been replaced
2) Only tweets from FOSSASIA are being displayed
Help me figure out the reaming,and I shall proceed! :sweat_smile: 
Thank you!

**Pull request closed without merging**
