### PR TITLE
#209 social icons resolved

### PR DESCRIPTION
**Pull request by aayusharora**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://aayusharora.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@aayusharora Yes, works fine.
Squash the commits, please ?

**Comment by jigyasa-grover** [comment]
@aayusharora This might help https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md , in case.

**Comment by aayusharora** [comment]
Can you guide in squashing ,my branch was 9 commits ahead earlier ,thats why it is showing so many commits ?

**Comment by aayusharora** [comment]
@jig08 ,I think its done ,Can you please check ?

**Comment by codethejason** [comment]
@aayusharora Run `git pull --rebase http://github.com/fossasia/gci15.fossasia.org` to get rid of the merge commit.

**Comment by mananwason** [comment]
@codethejason Would you like to add a topic on how to remove merge commits in http://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md?

**Comment by mananwason** [comment]
@aayusharora Closing this

**Comment by codethejason** [comment]
@mananwason Sure, will do it now.

**Pull request closed without merging**
