### PR TITLE
-added new student to students list (revolved merge commits)

### PR DESCRIPTION
**Pull request by Eclipse-Dominator**
Added Li Zhaoqi to the students list

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Eclipse-Dominator.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@Eclipse-Dominator Resolve merge commits.

**Comment by jigyasa-grover** [comment]
@Eclipse-Dominator Could you squash your commits as well, and then we shall merge this PR.

**Comment by Eclipse-Dominator** [comment]
I typed git rebase -i HEAD~2 but i was unable to locate commit 65b13f2 in the list, hence I am not sure on how to squash the 2 commits.

**Pull request closed without merging**
