### PR TITLE
Added curly quotations in bios.

### PR DESCRIPTION
**Pull request by Meta-Maxim**
Fancy quotation marks in bio blurbs.
quotes

### CODE REVIEW

**Comment by harshkothari410** [comment]
Can you place some padding to right quotations ?

**Comment by Meta-Maxim** [comment]
Uh yes doing that right now, only reason I used absolute was because when I increased quotation size, messed up the spacing between lines. Fixing.

**Comment by harshkothari410** [comment]
Let me know if you need any help.

**Comment by Meta-Maxim** [comment]
@harshkothari410 Fixed quote positioning.

**Comment by harshkothari410** [comment]
Thanks for this.

**Pull request merged**
