### PR TITLE
Fixed up the bottom footer section

### PR DESCRIPTION
**Pull request by codethejason**
Made footer look more appealing and informative.

### CODE REVIEW

**Comment by SaptakS** [comment]
Please stash all the commits into a single commit.. You can use git reset --soft for the purpose..

**Comment by codethejason** [comment]
I combined the other commits. The first commit (currently) adds content to footer (GCI task), and the second commit solves a pending reported issue unrelated to the footer itself. I feel like this would be the best organization when someone is looking over the commits.

**Comment by mananwason** [comment]
@codethejason resolve conflicts please

**Comment by codethejason** [comment]
@mananwason Resolved!

**Comment by mananwason** [comment]
@codethejason I believe that while rebasing, you didn't comment the other commit messages. Please rebase and add only one commit message. 
screen shot 2015-12-24 at 10 58 11 pm

**Comment by codethejason** [comment]
@mananwason Got rid of the other messages.

**Comment by mananwason** [comment]
Cool then. Merging :wink:

**Comment by roonyh** [comment]
This merge add some unnessary changes to `students.yml`. See [changed files](https://github.com/fossasia/gci15.fossasia.org/pull/181/files). @mananwason keep an eye on **Files changed** tab when you are merging :)

**Comment by codethejason** [comment]
Oops, sorry about that @roonyh. I did not notice that while rebasing.

**Comment by roonyh** [comment]
@codethejason no worries :) could you make a quick PR removing the duplicate entries?

**Comment by codethejason** [comment]
@roonyh Done: #200

**Comment by mananwason** [comment]
Sure @roonyh :)

**Pull request merged**
