### PR TITLE
#165 Resolved

### PR DESCRIPTION
**Pull request by aayusharora**

### CODE REVIEW

**Comment by yasoob** [comment]
Hey @aayusharora Can you kindly squash those commits together? :+1:

**Comment by mananwason** [comment]
@aayusharora Please remove merge commits and squash into one commit.

**Comment by yasoob** [comment]
Apart from multiple commits, the fix looks good to me. :smile:

**Comment by aayusharora** [comment]
@mananwason, @yasoob  Can you help in getting the right command for git in this case?

**Comment by mananwason** [comment]
@aayusharora look at this http://stackoverflow.com/questions/6406762/why-am-i-merging-remote-tracking-branch-origin-develop-into-develop

**Comment by aayusharora** [comment]
@mananwason  Its not working ,There are lot of commits after i commited ,Can you handle it or you can suggest any other approach.

**Comment by aayusharora** [comment]
Hi,@mananwason ,check #204 ,have created a new  branch with a single commit to merge .Is it fine now?

**Comment by mananwason** [comment]
Closing this then.

**Pull request closed without merging**
