### PR TITLE
Removed Google +

### LINKED ISSUE #768: Remove G+
Please remove the links to Google Plus present in the site as they are extinct.

### PR DESCRIPTION
**Pull request by NishithP2004**
Fixes #768

### CODE REVIEW

**Comment by NishithP2004** [comment]
@abishekvashok Please review

**Comment by NishithP2004** [comment]
@mariobehling Please review

**Comment by PriyanshSarvehi** [comment]
Sir,
May I work on this issue?

**Comment by codedsun** [comment]
@PriyanshSarvehi - We are looking for contributors on open-event project. Do clone that repo and get started

**Comment by PriyanshSarvehi** [comment]
> @PriyanshSarvehi - We are looking for contributors on open-event project. Do clone that repo and get started

On it sir 👍

**Comment by PriyanshSarvehi** [comment]
> @PriyanshSarvehi - We are looking for contributors on open-event project. Do clone that repo and get started

Can you also tell or let me in on other frontend projects?
I am willing to work full time 
I'm eger to learn and contribute

**Comment by codedsun** [comment]
@PriyanshSarvehi Open-event-frontend is the repo. You can clone and get started, ping us on gitter if you face any issues. We have bi-weekly meetings on Tues/Thursday at 7PM join that too to get started.

**Comment by PriyanshSarvehi** [comment]
@codedsun 
I'd love to work on it. Will start ASAP.

**Pull request closed without merging**
