### PR TITLE
Fixed g+ centering Issue #87

### PR DESCRIPTION
**Pull request by codethejason**

### CODE REVIEW

**Comment by Meta-Maxim** [comment]
@codethejason From now on please don't commit the files under _site. They are copies that are generated automatically by Jekyll and theres no need to commit them.

**Comment by codethejason** [comment]
No problem, I wasn't sure because others seem to be contributing to it. I'll removed those files and edit the readme.

**Comment by Meta-Maxim** [comment]
@codethejason Well, you can't remove them because they'll regenerate, just don't commit them. I'll add a .gitignore for it.

**Comment by codethejason** [comment]
@MaxBorsch There is already a gitignore, but it doesn't work automatically. They will regenerate but other contributors will be confused if they're contributing a brand new directory. We should remove stuff that can be regenerated from the repository.

**Comment by Meta-Maxim** [comment]
@codethejason No you didn't understand, Jekyll runs on Github, so every time you pull a new change to this repository, Jekyll will build the _site. You can't remove it, you can only avoid updating it with a gitignore. Also the .gitignore does work automatically, I just messed up at configuring it. You can add to the README to specify this until I figure out what's wrong with the gitignore.

**Comment by codethejason** [comment]
Oh, I see. In that case, I don't think it's possible to make an automatic gitignore because gitignore will only ignore files that have not already been added to the repository. If _site always exists, it's impossible for gitignore to exclude it. I'll change my pull request.

**Comment by seadog007** [comment]
@codethejason but it already merged, so you can't change this PR....

**Comment by codethejason** [comment]
@seadog007 We're talking about this commit: https://github.com/fossasia/gci15.fossasia.org/pull/99 . Let's move the conversation over there.

**Pull request merged**
