### PR TITLE
Added section blogs as a part of GCI

### PR DESCRIPTION
**Pull request by abishekvashok**
Added section blogs as a part of GCI in a user friendly manner with minimal code(no js[except to load content] only css). Also emphasised to save page load time. @jig08 @roonyh @sudheesh001 @SaptakS @niccokunzmann . Please review and accept(if possible) before any conflicts arrise

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@Abhi2424shek The blog links don't redirect to the post. Please check!!

**Comment by abishekvashok** [comment]
wait would make a new pr

**Comment by mananwason** [comment]
What about if you fix it in this PR only?

**Comment by abishekvashok** [comment]
ok but I am having trouble squashing commits @mananwason can you help me sir

**Comment by mananwason** [comment]
Sure @Abhi2424shek I helped a student [here](https://github.com/fossasia/gci15.fossasia.org/pull/442). Maybe you can follow this and let me know if you run into any issues. Cheers!

**Comment by abishekvashok** [comment]
Here's the link: https://github.com/fossasia/gci15.fossasia.org/pull/531 to the new PR, if there is any issue then I will ask you for help ok :)

**Pull request closed without merging**
