### PR TITLE
Added myself (Jason) and made mobile icons smaller

### PR DESCRIPTION
**Pull request by codethejason**

### CODE REVIEW

**Comment by codethejason** [comment]
Fixed issue #131

**Comment by codethejason** [comment]
The user can now may click on a user's face to go to their github. It is impractical to fit all the links in smaller version of the site. Also removed the hover dialogs and made some other small enhancements.

**Comment by hvardhanx** [comment]
Please resolve the conflicts.

**Comment by codethejason** [comment]
When I type `git merge fossasia/gh-pages --squash`, why do I get `(nothing to squash)Already up-to-date.`?

**Comment by codethejason** [comment]
Fixed conflicts.

**Pull request merged**
