### PR TITLE
Navbar tabs collapse on small size

### PR DESCRIPTION
**Pull request by Meta-Maxim**
Navbar headings now collapse into a dropdown on a smaller screen. Issue #322

Also added some nice colors to tabs.

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://MaxBorsch.github.io/gci15.fossasia.org

**Comment by jigyasa-grover** [comment]
@MaxBorsch Squash commits ?

**Comment by Meta-Maxim** [comment]
@jig08 Git doesn't seem to let me squash a the branch merge commit because it contains multiple commits under it.

**Comment by mananwason** [comment]
what do you mean @MaxBorsch?

**Comment by Meta-Maxim** [comment]
@mananwason First, when I attempt to rebase the last two commits with `git rebase -i HEAD~2` it shows me more than two commits in the rebase file (all of the commits that were under the pull). After the rebase it also errors and says it failed to rebase. Should I be using a different method to squash?

**Comment by mananwason** [comment]
@MaxBorsch I have described the method [here](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md). Tell me if you have done something else.

**Comment by jigyasa-grover** [comment]
@MaxBorsch Working on this ?

**Comment by Meta-Maxim** [comment]
@jig08 Oh yes, sorry I was busy with school. I'll do it later today.

**Comment by jigyasa-grover** [comment]
Cool !

**Pull request closed without merging**
