### PR TITLE
GCI Task

### PR DESCRIPTION
**Pull request by anukul**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://anukul.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@anukul remove the merge pull request commits. Thanks!

**Comment by samarjeet27** [comment]
Nice Work! But please squash your commits See [GIT.md](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md)

**Comment by sumsupee** [comment]
@anukul [Git.md](https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md) can be really helpful for removing those unwanted merge commits!

**Pull request closed without merging**
