### PR TITLE
Fixing some overflows on mobile

### LINKED ISSUE #746: Facebook widget and blog posts overflowing
image
image

We need to:
- [ ] Make Facebook widget responsive
- [ ] Make blog cards responsive

### PR DESCRIPTION
**Pull request by myfrom**
Fixed #746 

**BEFORE**
image
image

**AFTER**

witus13 github io-gci15 fossasia org- nexus 5x 1
witus13 github io-gci15 fossasia org- nexus 5x

[Demo](https://witus13.github.io/gci15.fossasia.org)
[GCI task](https://codein.withgoogle.com/dashboard/task-instances/6639049525690368/)

### CODE REVIEW

**Comment by abishekvashok** [comment]
Can you add an after and before PR screenshot

**Comment by myfrom** [comment]
@Abhi2424shek You mean screenshots?

**Comment by abishekvashok** [comment]
Yep

**Comment by myfrom** [comment]
@Abhi2424shek Done, updated the description

**Review by daminisatya — APPROVED** [review]
Well, I liked the fix @Witus13 :) and also thank you @Abhi2424shek for suggestions :D

**Comment by abishekvashok** [comment]
@daminisatya no mentions pls

**Pull request merged**
