### PR TITLE
closes #157

### LINKED ISSUE #157: Navbar hamburger has disappeared
There is no navbar hamburger on the main screen of the site now:
f2mlhby4qzm
It changes its positions:
g-axqsunufk

**But actually it works okay from the browser's adaptive view.**

Could someone also check this?

### PR DESCRIPTION
**Pull request by yasoob**
I hope it's good to merge. :smile:

### CODE REVIEW

**Comment by mananwason** [comment]
@yasoob Please point me to your gh page where this is deployed. I can't seem to open this. I would like to review it first :wink:

**Comment by yasoob** [comment]
Sorry. I had updated my code in a separate `patch` branch. I have merged it with my `gh-pages` branch. You can view the `gh-pages` over [here](http://yasoob.me/gci15.fossasia.org/)

**Comment by mananwason** [comment]
Still not solved !!
screenshot_20151224-220903

**Comment by yasoob** [comment]
Sorry my bad. Kindly try again :)

**Comment by mananwason** [comment]
Nice work :smile:. Merging this :+1:

**Pull request merged**
