### PR TITLE
Added --- which is a requirement of jekyll closes #712

### LINKED ISSUE #712: Mentors and students dont show
screen shot 2016-01-27 at 4 15 37 pm
anyone else having this issue?

### PR DESCRIPTION
**Pull request by yasoob**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://yasoob.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
Oh. Which commit changed this?

**Comment by jmurzaku** [comment]
https://github.com/codethejason/gci15.fossasia.org/commit/74e113c4e015d41158e05d565ef11b616447302e the --- was probably accidentally removed @mananwason

**Comment by mananwason** [comment]
Yeah just saw that @JamMurz. :smile: This was in #707

**Comment by codethejason** [comment]
@mananwason Sorry, I was doing some quick changes w/o running Jekyll and wanted to do some header changes and I forgot to add them back in.

**Comment by mananwason** [comment]
No issues @codethejason :grinning:

**Pull request merged**
