### PR TITLE
Added Copyright Details

### PR DESCRIPTION
**Pull request by Elgayar**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Elgayar.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@Elgayar there are conflicts in your code, please fix them and then we can merge. Thanks!

**Comment by Elgayar** [comment]
What are the conflicts in my code so I can fix them?

**Comment by mananwason** [comment]
@Elgayar You need to check that on your machine

**Comment by Elgayar** [comment]
@mananwason Sorry, but I can't spot a mistake, I have added the bootstrap class so it would be responsive in the center bottom of the page, what else should I do?

**Comment by codethejason** [comment]
@Elgayar Try following this guide: https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md. Others have modified the same file and area as you have during the time you changed the code, so you need to pull the changes into your fork to be able to pull request a compatible version of the code to FOSSASIA.

**Comment by yasoob** [comment]
@Elgayar if anything is still not clear then kindly let us know so that we can further assist you. Best of luck! :+1:

**Comment by Elgayar** [comment]
https://github.com/fossasia/gci15.fossasia.org/pull/631

New Pull Request

**Comment by yasoob** [comment]
@Elgayar kindly close this PR then :smile:

**Comment by Elgayar** [comment]
@yasoob Closed it

**Pull request closed without merging**
