### PR TITLE
Fixed social media icons and g+ alignment

### LINKED ISSUE #53: Icon display problem
When the icon display, it look like very weird.
- 3:
  
- 4:

### PR DESCRIPTION
**Pull request by codethejason**

### CODE REVIEW

**Comment by seadog007** [comment]
Well, it still not align properly

**Comment by codethejason** [comment]
Screenshot?

**Comment by seadog007** [comment]
It only happen on Github icon

**Comment by codethejason** [comment]
@seadog007 Thanks, I'll look into it.

**Comment by seadog007** [comment]
And also the vertical align of Facebook icon

**Comment by codethejason** [comment]
Thanks, both issues should be fixed now.

**Comment by harshkothari410** [comment]
Please resolve conflict and send pull request again

**Comment by codethejason** [comment]
Done!

**Pull request merged**
