### PR TITLE
Adding my info for FOSSASIA website for the students section..

### PR DESCRIPTION
**Pull request by S-ulphuric**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://S-ulphuric.github.io/gci15.fossasia.org

**Comment by samarsault** [comment]
@S-ulphuric please make the PR title a little more descriptive such as "Adding my information to the GCI students section"
Also, Please Squash your commits.
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by S-ulphuric** [comment]
Is it now ok..

**Comment by jig08** [comment]
@S-ulphuric Kindly squash your commits.
This could be of help https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md :)

**Comment by mananwason** [comment]
@jig08 Please don't merge if commits are not squashed. There are 3 commits here. I am reverting this for now.

**Comment by jigyasa-grover** [comment]
@mananwason :+1:

**Comment by jigyasa-grover** [comment]
@S-ulphuric Kindly squash commits. This might help https://github.com/fossasia/gci15.fossasia.org/blob/gh-pages/GIT.md

**Comment by S-ulphuric** [comment]
I'm having problems, whenever I'm trying to squash my commits its giving me an error. Please help me here.

**Comment by mananwason** [comment]
@S-ulphuric What is the error?

**Comment by S-ulphuric** [comment]
screenshot

**Pull request merged**
