### PR TITLE
Update stylesheet.css

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Added red scrolldown
https://arjunpandey2003.github.io/gci15.trufossasiabcdef.org/.

### CODE REVIEW

**Comment by abishekvashok** [comment]
Gallery shows a blue underline, pls check it

**Comment by arjunpandey2003** [comment]
@abishekvashok thats already a part of the current website

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Don't change those icons pls

**Comment by arjunpandey2003** [comment]
@abishekvashok that is why my travis is failing it must be 240x240 or less

**Comment by abishekvashok** [comment]
Hmm, we can ignore the tests i for this one I guess. But since you have changed it it's fine

**Review by ParthS007 — APPROVED** [review]

**Comment by arjunpandey2003** [comment]
thanks

**Comment by arjunpandey2003** [comment]
Can we merge

**Comment by ParthS007** [comment]
@arjunpandey2003 Please wait for other mentors to review. 👍

**Comment by arjunpandey2003** [comment]
sure

**Review by akshatnitd — COMMENTED** [review]
I saw the demo link. It would be better if you could make the design of the drop-down items uniform. Some items do not have a bottom-border as others have.

**Review by nzec — CHANGES_REQUESTED** [review]
Use FOSSASIA Red instead of Pure Red.

**Review by akshatnitd — APPROVED** [review]

**Comment by arjunpandey2003** [comment]
pls merge

**Review by sayak119 — APPROVED** [review]

**Comment by mariobehling** [comment]
There was no issue for this here and it does not really fit to the design which is different to the FOSSASIA standard sites. Therefore reverting it.

**Pull request merged**
