### PR TITLE
Modified Students gallery section

### PR DESCRIPTION
**Pull request by neerajp99**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://neerajp99.github.io/gci15.fossasia.org

**Comment by mananwason** [comment]
@neerajp99 Nice work.  What about you add arrow key support  to the Gallery frame so that we can navigate between the items.

**Comment by neerajp99** [comment]
This looks much better becuase if i add arrow keys at the left and right ends they will collapse with the images :)

Also that will take a long time ..as already i have devoted a lot time in this 
:+1:

**Comment by neerajp99** [comment]
This looks much better becuase if i add arrow keys at the left and right ends they will collapse with the images :)

Also that will take a lot of time ..as already i have devoted a lot time in this 
:+1:

**Comment by mananwason** [comment]
No I mean that if I click arrow key on my keyboard, it should move to next item. That shouldn't take much time.

**Comment by neerajp99** [comment]
Hey manan , 
In this section the images are moving not the section is sliding ,if the whole would be sliding then i would have used e.keycode to navigate it 

So its not possible .

I think this one also looks good.

**Comment by neerajp99** [comment]
I tried using these type of codes:

 <script>
   new Photostack(document.getElementById('photostack-1'), {
        callback: function(item) {
            //console.log(item)
         }
     });

```
  $('.photostack').photostack({
```

  auto: true,
  autoControls: true
});
      </script>

```
  <script>
```

$(document).keydown(function(e) {
    var checkedElmIdx =  parseInt($("[type='radio']:checked").attr("id").split("_")[1]);
   if(e.keyCode == 37) { // left
       $("#img_1"+(checkedElmIdx-1)).prop("checked", true);
   } else if(e.keyCode == 39) { // right
        $("#img_2"+(checkedElmIdx+1)).prop("checked", true);
   }
});
</script>

Also the gallery will keep on increasing and at that time it will not be possible to change the js each time for each image 
:)

**Comment by mananwason** [comment]
Oh okay. No issues. My concern was that it would be difficult to move b/w items by clicking the indicators. Anyways, I'l merge it. Nice work :smiley:

**Pull request merged**
