### PR TITLE
Fixed #26 and fixed #39

### LINKED ISSUE #26: Non responsive navbar
There is something wrong happening with the current nav bar. It has some margin collisions with the slider when it is getting smaller.

Also the logo stays fixed on smaller screens and the nav bar doesn't. It makes the site look bad at smartphones.

As I see one issue is cause because bootstrap-responsive adds:

```
body {
    padding-left: 20px;
    padding-right: 20px;
}
```

and I am not very sure about the other one.

selection_003
selection_004

It would be nice if someone fixed it.

### LINKED ISSUE #39: Incorrect margin sizes for container
The margins on the left and right sides of the site are not the same size as shown in the image below. This is a problem because all of the page content is shifted slightly in a certain direction.

margins

### PR DESCRIPTION
**Pull request by pythad**
I am not sure who and for what added 
`<link rel="stylesheet" type="text/css" href="stylesheets/bootstrap-responsive.css" media="screen">`
to the code but it doesn't make anything good at all, it just adds some unnecessary paddings and margins. Deleting it caused fixes for bugs #26 and #39.

[Demo](http://pythad.github.io/gci15.fossasia.org/)

### CODE REVIEW

**Comment by harshkothari410** [comment]
keep that thing. I have another idea to fix this.

**Comment by pythad** [comment]
@harshkothari410, why do we need to keep it if we don't use it, it just make the site slower?

**Comment by harshkothari410** [comment]
Okies. It might be useful further. By the way your fix does not work. In the Demo link it shows me as it is.

**Comment by pythad** [comment]
@harshkothari410 , But we don't use it now and probably will never use it.
It seems strange, it works for me okay, it has to work as bootstrap-responsive added unnecessary margins.
selection_007

**Pull request merged**
