### PR TITLE
Added Arrows as stated by Admin as a part of GCI

### PR DESCRIPTION
**Pull request by abishekvashok**

### CODE REVIEW

**Comment by prwatch** [comment]
DEMO: http://Abhi2424shek.github.io/gci15.fossasia.org

**Comment by abishekvashok** [comment]
@roonyh take a look now and accept my task it works like a fly!

**Comment by roonyh** [comment]
Good job!  
In future tasks please avoid making too much noice. We already get a notification when you make a PR so no need of additional comments if you don't have anything to add.

Thanks!

**Comment by abishekvashok** [comment]
@roonyh be sure to accept my task too!

**Comment by abishekvashok** [comment]
@roonyh really sorry for that really really sorry (after all I am a Malayali ! from kerala)
and again sorry sir respecting all of you and really sorry

**Comment by roonyh** [comment]
Will do, when you mark it as to review.

**Comment by abishekvashok** [comment]
Marked!

**Comment by roonyh** [comment]
Approved! Don't worry about it. Good communication is important in open source communities and you are here to learn :)

Hope to see more good work from you.

**Comment by abishekvashok** [comment]
Ok can you wait an hour online or log in after one hour!

**Pull request merged**
